### ISSUE TITLE
LogManager.Default.GetLogger() fails when an ILogManager implementation has not been registered

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1013]
I noticed this when constructing a `GatedTimer` for the **RaspberryDebug** project.  I saw a `System.TypeInitializationException`.

**PROBLEM:**  It looks like `ServiceContainer` needs to implement a generic `GetEnumerator()` method:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Neon.Diagnostics.LogManager' threw an exception.
  Source=Neon.Common
  StackTrace:
   at Neon.Time.GatedTimer..ctor(TimerCallback callback, Object state, TimeSpan dueTime, TimeSpan period)
   at Neon.Time.GatedTimer..ctor(TimerCallback callback, Object state, TimeSpan period)
   at RaspberryDebug.PackageHelper.ProgressUpdater..ctor(IVsThreadedWaitDialog2 progressDialog, Int32 targetSeconds, Int32 maxTargetSeconds) in C:\src\RaspberryDebug\RaspberryDebug\PackageHelper.cs:line 228

Inner Exception 1:
MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.Extensions.DependencyInjection.ServiceDescriptor> Microsoft.Extensions.DependencyInjection.ServiceCollection.GetEnumerator()'.
```

**Comment by jefflill** [comment]
Our `ServiceContainer` already has a generic enumerator.  I did some googling and see that folks are saying the problem is due to package version conflicts:

https://github.com/dotnet/efcore/issues/8498

I'm going to close this as a special case with the VSIX project and use the stock timer there.
