### ISSUE TITLE
Cluster Setup: JsonReaderException

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1054]
@marcusbooyah: I'm seeing a `JsonReaderException` when trying to setup a cluster.  This is happening in `ClusterSetupCommand.cs`  on **line 2256**:
```
            master.InvokeIdempotentAction("setup/neon-storage-openebs-cstor-poolcluster",
                   () =>
                   {
                       var cStorPoolCluster = new V1CStorPoolCluster()
                       {
                           Metadata = new V1ObjectMeta()
                           {
                               Name = "cspc-stripe",
                               NamespaceProperty = "openebs"
                           },
                           Spec = new V1CStorPoolClusterSpec()
                           {
                               Pools = new List<V1CStorPoolSpec>()
                           }
                       };

                       // **EXCEPTION HAPPENS HERE:
                       var blockDevices = ((JObject)k8sClient.ListNamespacedCustomObjectAsync("openebs.io", "v1alpha1", "openebs", "blockdevices").Result).ToObject<V1CStorBlockDeviceList>();
```
Here are the exception details:
```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error reading string. Unexpected token: StartObject. Path 'items[0].spec.devlinks[0]'.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at NeonCli.ClusterSetupCommand.<>c__DisplayClass37_0.<InstallOpenEBSAsync>b__3() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 2256

  This exception was originally thrown at this call stack:
    [External Code]
    NeonCli.ClusterSetupCommand.InstallOpenEBSAsync.AnonymousMethod__3() in ClusterSetupCommand.cs
```
Here's my cluster definition:
```
name: home-small
datacenter: sultan
environment: development
linuxDistribution: ubuntu
linuxVersion: 20.04.latest
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: hyperv-local
  vm:
    diskLocation: D:\\VM
network:
  premiseSubnet: 10.0.0.0/16
nodeOptions:
  upgrade: none
nodes:
  master-0:
    role: master
    address: 10.0.1.30
  worker-0:
    role: worker
    address: 10.0.1.40
  worker-1:
    role: worker
    address: 10.0.1.41
  worker-2:
    role: worker
    address: 10.0.1.42
```
**NOTE:** I'm working in the **jeff** branch but that's fully synced with **master**

**Comment by jefflill** [comment]
On a related note, I've been also seeing several code comment warnings for a while now:

![image](https://user-images.githubusercontent.com/4908431/98140658-8a4bd100-1e7a-11eb-8108-a17905f9c92a.png)

How about some comments with actual sentences?   :)

**Comment by marcusbooyah** [comment]
Turns out devlinks are actually a thing on Hyper-V. I added the classes for them.
