### ISSUE TITLE
Cluster setup fails when OpenEBS disk size isn't specified in cluster definition

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1064]
Here's the exception from the setup log:
```
*** ERROR: [FormatException]: Cannot parse the [] ByteUnits.
*** STACK:    at Neon.Common.ByteUnits.Parse(String text) in C:\src\neonKUBE\Lib\Neon.Common\Misc\ByteUnits.cs:line 283
   at NeonCli.ClusterSetupCommand.<>c.<InstallOpenEBSAsync>b__39_17(NodeDefinition n) in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 2346
   at System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector)
   at NeonCli.ClusterSetupCommand.<>c__DisplayClass39_0.<<InstallOpenEBSAsync>b__6>d.MoveNext() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 2346
--- End of stack trace from previous location where exception was thrown ---
   at Neon.SSH.LinuxSshProxy`1.InvokeIdempotentActionAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.SSH\LinuxSshProxyT.cs:line 3175
   at NeonCli.ClusterSetupCommand.InstallOpenEBSAsync(NodeSshProxy`1 master) in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 2342
   at NeonCli.ClusterSetupCommand.<>c__DisplayClass33_0.<<SetupClusterAsync>b__3>d.MoveNext() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 1737
--- End of stack trace from previous location where exception was thrown ---
   at Neon.SSH.LinuxSshProxy`1.InvokeIdempotentActionAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.SSH\LinuxSshProxyT.cs:line 3175
   at NeonCli.ClusterSetupCommand.SetupClusterAsync() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 1734
   at Neon.Kube.SetupController`1.<>c__DisplayClass41_0.<<PerformStep>b__7>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\Setup\SetupController.cs:line 759
```

**Comment by jefflill** [comment]
- [ ] The fix is to call `node.GetOpenEbsDisk()` instead of referencing `node.Vm.OpenEbsDisk` directly.  The get method handles the default (`null`) values correctly by using the cluster default.

- [ ] Also, the `OpenEbs` property should be at the node level rather than be in `VmOptions` since this applies to bare metal deployments as well.  I'll fix this as well.

**Comment by jefflill** [comment]
FIXED
