### ISSUE TITLE
Timeout waiting for Redis

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1066]
I was setting up 4 node cluster on XCP-ng (1 master, 3 workers) and got pretty far this time to:

    setup cluster/deploy: registry

This ended up timing out though after the 10 minute wait time.  I tried restarting setup but the same thing happened.  The action is happening on this line:
```
return statefulsets.Items.All(p => p.Status.ReadyReplicas == p.Spec.Replicas);
```
There's one item in `statefulsets` and `p.Spec.Replicas==3` for that item.  Here's what all the properties look like:

![image](https://user-images.githubusercontent.com/4908431/98430941-20901a80-2066-11eb-8f7e-f0657f706c64.png)

Here's the last bit of the setup log for the **master:**
```
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh
#!/bin/bash
cd /tmp/charts

until [ -f redis-ha.zip ]
do
  sleep 1
done

rm -rf redis-ha

unzip redis-ha.zip -d redis-ha
helm install neon-system-registry-redis redis-ha --namespace neon-system -f redis-ha/values.yaml  --timeout 300s 

START=`date +%s`
DEPLOY_END=$((START+15))

until [ `helm status neon-system-registry-redis --namespace neon-system | grep "STATUS: deployed" | wc -l` -eq 1  ];
do
  if [ $((`date +%s`)) -gt $DEPLOY_END ]; then
    helm delete neon-system-registry-redis || true
    exit 1
  fi
   sleep 1
done

rm -rf redis-ha*
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/7f920bcd-ea94-437f-bf57-eba63ca7674a/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-440b038b-c851-4a26-9525-2ceacad7339a" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-440b038b-c851-4a26-9525-2ceacad7339a" ; fi'
END [OK]
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/7f920bcd-ea94-437f-bf57-eba63ca7674a'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/deploy/neon-system-registry-redis'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/deploy'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/deploy/neon-system-registry-redis-ready" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** ERROR: [TimeoutException]: Timeout waiting for the predicate to return TRUE.
*** ERROR: [TimeoutException]: Timeout waiting for the predicate to return TRUE.
*** STACK:    at Neon.Common.NeonHelper.WaitForAsync(Func`1 predicate, TimeSpan timeout, Nullable`1 pollInterval, String timeoutMessage) in C:\src\neonKUBE\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 460
   at NeonCli.ClusterSetupCommand.<>c__DisplayClass50_0.<<InstallNeonRegistryAsync>b__2>d.MoveNext() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 3078
--- End of stack trace from previous location where exception was thrown ---
   at Neon.SSH.LinuxSshProxy`1.InvokeIdempotentActionAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.SSH\LinuxSshProxyT.cs:line 3175
   at NeonCli.ClusterSetupCommand.InstallNeonRegistryAsync(NodeSshProxy`1 master) in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 3075
   at NeonCli.ClusterSetupCommand.<>c__DisplayClass33_0.<<SetupClusterAsync>b__7>d.MoveNext() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 1777
--- End of stack trace from previous location where exception was thrown ---
   at Neon.SSH.LinuxSshProxy`1.InvokeIdempotentActionAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.SSH\LinuxSshProxyT.cs:line 3175
   at NeonCli.ClusterSetupCommand.SetupClusterAsync() in C:\src\neonKUBE\Tools\neon-cli\Commands\Cluster\ClusterSetupCommand.cs:line 1774
   at Neon.Kube.SetupController`1.<>c__DisplayClass41_0.<<PerformStep>b__7>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\Setup\SetupController.cs:line 759
# CLUSTER-END-SETUP-FAILED #######################################################
```

**Comment by jefflill** [comment]
@marcusbooyah fixed this
