### ISSUE TITLE
Setup cluster failing on Hyper-V

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1138]
I'm trying to setup a variation of a 3 node small cluster with one master and two worker and with all nodes assigned 10GB RAM and am seeing a crash within the **setup cluster** step.  Here's the failing last entry from the setup log:
```
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

systemctl enable kubelet.service
kubeadm init --config cluster.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests
*** END TEXT FILE
*** START TEXT FILE: cluster.yaml

apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: home-small
kubernetesVersion: "v1.19.5"
imageRepository: "neon-registry.node.local"
apiServer:
  extraArgs:
    bind-address: 0.0.0.0
    logging-format: json
    default-not-ready-toleration-seconds: "30" # default 300
    default-unreachable-toleration-seconds: "30" #default  300
    allow-privileged: "true"
  certSANs:
  - "10.0.1.30"

controlPlaneEndpoint: "kubernetes-masters:6442"
networking:
  podSubnet: "10.254.0.0/16"
  serviceSubnet: "10.253.0.0/16"
controllerManager:
  extraArgs:
    logging-format: json
    node-monitor-grace-period: 15s #default 40s
    node-monitor-period: 5s #default 5s
    pod-eviction-timeout: 30s #default 5m0s
scheduler:
  extraArgs:
    logging-format: json

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
logging:
  format: json
nodeStatusReportFrequency: 4s
volumePluginDir: /var/lib/kubelet/volume-plugins


*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/8768588f-fea5-4f4d-8733-8090ee460cf6/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-6c06aa1e-dba1-446b-bbe9-9e9b97290604" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-6c06aa1e-dba1-446b-bbe9-9e9b97290604" ; fi'
END [OK]
    [init] Using Kubernetes version: v1.19.5
    [preflight] Running pre-flight checks
STDERR
    Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /lib/systemd/system/kubelet.service.
    W0222 19:46:49.118137    3244 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
    error execution phase preflight: [preflight] Some fatal errors occurred:
    	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
    [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    To see the stack trace of this error execute with --v=5 or higher
END [ERROR=1]
*** STATUS: ERROR[1]
*** ERROR: [RemoteCommandException]: [exitcode=1]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/8768588f-fea5-4f4d-8733-8090ee460cf6 && /bin/bash ./__run.sh'

*** ERROR: [RemoteCommandException]: [exitcode=1]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/8768588f-fea5-4f4d-8733-8090ee460cf6 && /bin/bash ./__run.sh'

*** STACK:    at Neon.SSH.LinuxSshProxy.RunCommand(String command, RunOptions runOptions, Object[] args)
   at Neon.SSH.LinuxSshProxy.SudoCommand(String command, RunOptions runOptions, Object[] args)
   at Neon.SSH.LinuxSshProxy.SudoCommand(CommandBundle bundle, RunOptions runOptions)
   at Neon.Kube.KubeSetup.<>c__DisplayClass20_0.<ConfigureKubernetes>b__1()
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action)
   at Neon.Kube.KubeSetup.<>c__DisplayClass20_0.<ConfigureKubernetes>b__0()
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action)
   at Neon.Kube.KubeSetup.ConfigureKubernetes(ObjectDictionary setupState, NodeSshProxy`1 firstMaster)
   at Neon.Kube.KubeSetup.SetupClusterAsync(ObjectDictionary setupState, Int32 maxParallel)
   at Neon.Kube.SetupController`1.<>c__DisplayClass49_0.<<PerformStep>b__8>d.MoveNext()
# CLUSTER-END-SETUP-FAILED #######################################################
```

**Comment by jefflill** [comment]
This is a couple years old but might be relevant:

https://github.com/kubernetes/kubeadm/issues/1062

**Comment by jefflill** [comment]
@marcusbooyah: this is still a problem after rebuilding the hyper-v node image (and fixing some neon-image bugs that was preventing me from rebuilding them).

This looks like an actual issue for you to look at.

**Comment by jefflill** [comment]
**FIXED**
