### ISSUE TITLE
Cluster setup [debug] mode

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1141]
We need to implement cluster setup debug mode because the developer inner-loop is horrible if you need to rebuild the node image for every change (which takes about an hour).

The idea is to be able to run cluster setup the **_old way_**, where we start nodes from the base image and then install and configure everything we need rather than relying on assets being already pre-positioned as they are in the node images we use during normal cluster setup.  Fortunately, we've been planning for this and we just need to wire up a few things.

**neon cluster prepare:**

Add the `--debug` and `--base-image-name` options. `--debug` sets the debug mode.  `--base-image-name` is required for debug mode and specifies the name of the base image as persisted to our **public S3 bucket**.  This will be required for `--debug`  mode.

![image](https://user-images.githubusercontent.com/4908431/109403461-94567b80-7912-11eb-89f2-a08e5bcb446a.png)

These will set the new setup controller **KubeSetup.DebugSetupProperty** ("debug-mode") setup controller state property to TRUE and the **KubeSetup.BaseImageName** property to the base `--base-image-name`.

**neon cluster setup:**

I'm also going to add the `--debug` option the the `neon cluster setup ...` command to enable debug mode.  This also implies  `--upload-charts`.

Here are the other changes we'll need to make, based on this mode:

- [x] Hosting managers (non-cloud) need to deploy base images rather than node images for debug mode:
    - [x] HyperV
    - [x] WSL2
    - [x] XenServer
- [x] Debug mode doesn't make sense for these hosting managers so they should throw a `NotSupportedException` when in this mode:
    - [x] Aws
    - [x] Azure
    - [x] BareMetal
    - [x] Google
- [x] Containers will need to be obtained from our GitHub registry so Helm chart references will need to be updated.  I believe Marcus already has an abstraction (the values file) to accomplish this.

I think that's it.  These changes will apply to both the community and enterprise edition of **neon-cli**.

**Comment by jefflill** [comment]
I've coded this and pushed both repos to master.  You need to recognize that we're in `--debug` mode and modify your Helm charts to reference the GitHub package repo in that case.

**Comment by jefflill** [comment]
@marcusbooyah: I'm going to have a go at tweaking this final step.

**Comment by jefflill** [comment]
While refactoring setup for **debug mode**, I've noticed a few things that need to be cleaned up:

- [ ] Most of the `NodeSshProxy` base, prepare, and setup methods need to include the **setup state** and **statusWriter** parameters and these values need to be passed thru to any sub-methods.
- [ ] `KubeHelper.WriteStatus()` needs to be called where ever the `LinuxSshProxy.Status` property is set.
- [ ] Status needs to be updated **within** the idempotent lambda, not outside.
- [ ] We need to be writing status in more places.  This is logged so it will help a lot with debugging.
- [ ] The idempotent action IDs need to start with either **"base/..."** or **"setup/...**, by convention.
- [ ] I'm going to tweak some of the action IDs

**Comment by jefflill** [comment]
**FYI** @marcusbooyah: I've noticed some case where cluster setup isn't performing some operations explicitly and instead is relying on these things to already be configured on the node image.  This breaks `--debug` mode which is starting from a base image instead of a node image.  Examples:

    CRI-O setup
    Podman setup

The model here is that cluster setup should always perform all required steps explicitly.  Any steps that have already been completed during node image prep will just be NOPs due to idempotent file presence.

**Comment by jefflill** [comment]
**FYI:** We'll need to **clear local image caches** and **rebuild all base & node images** because I changed a bunch of idempotent action IDs.

**Comment by jefflill** [comment]
..almost there.  I just realized that we need to publish the special Kubernetes, etc. container images with their original tags **as well as** the neonKUBE version tags.  I need to update the publish script and republish the images.

**Comment by jefflill** [comment]
@marcusbooyah: I was hoping to close this one but `--debug` mode setup failed with the log below.  Perhaps we need to retry this call like for #1144?
```
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/fde3dcfc-8054-43dc-9178-ab3ba4568b09/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-561e182b-2d51-44fb-b621-4e3879649cf3" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-561e182b-2d51-44fb-b621-4e3879649cf3" ; fi'
END [OK]
    [init] Using Kubernetes version: v1.19.5
    [preflight] Running pre-flight checks
    [preflight] Pulling images required for setting up a Kubernetes cluster
    [preflight] This might take a minute or two, depending on the speed of your internet connection
    [preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
    [certs] Using certificateDir folder "/etc/kubernetes/pki"
    [certs] Generating "ca" certificate and key
    [certs] Generating "apiserver" certificate and key
    [certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes-masters kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local master-0] and IPs [10.253.0.1 10.0.1.30]
    [certs] Generating "apiserver-kubelet-client" certificate and key
    [certs] Generating "front-proxy-ca" certificate and key
    [certs] Generating "front-proxy-client" certificate and key
    [certs] Generating "etcd/ca" certificate and key
    [certs] Generating "etcd/server" certificate and key
    [certs] etcd/server serving cert is signed for DNS names [localhost master-0] and IPs [10.0.1.30 127.0.0.1 ::1]
    [certs] Generating "etcd/peer" certificate and key
    [certs] etcd/peer serving cert is signed for DNS names [localhost master-0] and IPs [10.0.1.30 127.0.0.1 ::1]
    [certs] Generating "etcd/healthcheck-client" certificate and key
    [certs] Generating "apiserver-etcd-client" certificate and key
    [certs] Generating "sa" key and public key
    [kubeconfig] Using kubeconfig folder "/etc/kubernetes"
    [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
    [kubeconfig] Writing "admin.conf" kubeconfig file
    [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
    [kubeconfig] Writing "kubelet.conf" kubeconfig file
    [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
    [kubeconfig] Writing "controller-manager.conf" kubeconfig file
    [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
    [kubeconfig] Writing "scheduler.conf" kubeconfig file
    [kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
    [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
    [kubelet-start] Starting the kubelet
    [control-plane] Using manifest folder "/etc/kubernetes/manifests"
    [control-plane] Creating static Pod manifest for "kube-apiserver"
    [control-plane] Creating static Pod manifest for "kube-controller-manager"
    [control-plane] Creating static Pod manifest for "kube-scheduler"
    [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
    [wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
    [kubelet-check] Initial timeout of 40s passed.
    
    	Unfortunately, an error has occurred:
    		timed out waiting for the condition
    
    	This error is likely caused by:
    		- The kubelet is not running
    		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)
    
    	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
    		- 'systemctl status kubelet'
    		- 'journalctl -xeu kubelet'
    
    	Additionally, a control plane component may have crashed or exited when started by the container runtime.
    	To troubleshoot, list all containers using your preferred container runtimes CLI.
    
    	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
    		- 'crictl --runtime-endpoint /var/run/crio/crio.sock ps -a | grep kube | grep -v pause'
    		Once you have found the failing container, you can inspect its logs with:
    		- 'crictl --runtime-endpoint /var/run/crio/crio.sock logs CONTAINERID'
    
STDERR
    Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /lib/systemd/system/kubelet.service.
    W0303 20:26:57.979682    1540 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
    error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
    To see the stack trace of this error execute with --v=5 or higher
END [ERROR=1]
*** STATUS: ERROR[1]
*** ERROR: [RemoteCommandException]: [exitcode=1]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/fde3dcfc-8054-43dc-9178-ab3ba4568b09 && /bin/bash ./__run.sh'

*** ERROR: [RemoteCommandException]: [exitcode=1]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/fde3dcfc-8054-43dc-9178-ab3ba4568b09 && /bin/bash ./__run.sh'

*** STACK:    at Neon.SSH.LinuxSshProxy.RunCommand(String command, RunOptions runOptions, Object[] args)
   at Neon.SSH.LinuxSshProxy.SudoCommand(String command, RunOptions runOptions, Object[] args)
   at Neon.SSH.LinuxSshProxy.SudoCommand(CommandBundle bundle, RunOptions runOptions)
   at Neon.Kube.KubeSetup.<>c__DisplayClass22_0.<ConfigureKubernetes>b__1()
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action)
   at Neon.Kube.KubeSetup.<>c__DisplayClass22_0.<ConfigureKubernetes>b__0()
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action)
   at Neon.Kube.KubeSetup.ConfigureKubernetes(ObjectDictionary setupState, NodeSshProxy`1 firstMaster, Action`1 statusWriter)
   at Neon.Kube.KubeSetup.SetupClusterAsync(ObjectDictionary setupState, Int32 maxParallel, Action`1 statusWriter)
   at Neon.Kube.SetupController`1.<>c__DisplayClass49_0.<<PerformStep>b__8>d.MoveNext()
# CLUSTER-END-SETUP-FAILED #######################################################
```

**Comment by jefflill** [comment]
Closing this one.  @marcusbooyah has debug mode working now.
