### ISSUE TITLE
Debug Cluster Setup: Isto transient

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1150]
I had a cluster setup failure configuring Istio:
```
*** STATUS: setup: istio
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh
tmp=$(mktemp -d /tmp/istioctl.XXXXXX)
cd "$tmp" || exit
curl -fsLO https://github.com/istio/istio/releases/download/1.7.6/istioctl-1.7.6-linux-amd64.tar.gz
tar -xzf "istioctl-1.7.6-linux-amd64.tar.gz"
# setup istioctl
cd "$HOME" || exit
mkdir -p ".istioctl/bin"
mv "${tmp}/istioctl" ".istioctl/bin/istioctl"
chmod +x ".istioctl/bin/istioctl"
rm -r "${tmp}"
export PATH=$PATH:$HOME/.istioctl/bin
istioctl operator init --hub=ghcr.io/neonrelease-dev --tag=1.7.6-distroless
kubectl create ns istio-system
cat <<EOF > istio-cni.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: ghcr.io/neonrelease-dev
  tag: 1.7.6-distroless
  meshConfig:
    rootNamespace: istio-system
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
        service:
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 30080
          - name: https
            protocol: TCP
            port: 443
            targetPort: 8443
            nodePort: 30443
          - name: tls
            protocol: TCP
            port: 15443
            targetPort: 15443
            nodePort: 31922
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        strategy:
          rollingUpdate:
            maxSurge: "100%"
            maxUnavailable: "25%"
    cni:
      enabled: true
      namespace: kube-system
  values:
    global:
      logging:
        level: "default:info"
      logAsJson: true
      imagePullPolicy: IfNotPresent
      defaultNodeSelector: 
        neonkube.io/istio: true
      tracer:
        zipkin:
          address: neon-logging-jaeger-collector.monitoring.svc.cluster.local:9411
    pilot:
      traceSampling: 100
    meshConfig:
      accessLogFile: ""
      accessLogFormat: '{   "authority": "%REQ(:AUTHORITY)%",   "mode": "%PROTOCOL%",   "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",   "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",   "duration": "%DURATION%",   "request_duration": "%REQUEST_DURATION%",   "response_duration": "%RESPONSE_DURATION%",   "response_tx_duration": "%RESPONSE_TX_DURATION%",   "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",   "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",   "route_name": "%ROUTE_NAME%",   "response_code": "%RESPONSE_CODE%",   "response_code_details": "%RESPONSE_CODE_DETAILS%",   "user_agent": "%REQ(USER-AGENT)%",   "response_flags": "%RESPONSE_FLAGS%",   "start_time": "%START_TIME(%s.%6f)%",   "method": "%REQ(:METHOD)%",   "host": "%REQ(:Host)%",   "referer": "%REQ(:Referer)%",   "request_id": "%REQ(X-REQUEST-ID)%",   "forwarded_host": "%REQ(X-FORWARDED-HOST)%",   "forwarded_proto": "%REQ(X-FORWARDED-PROTO)%",   "upstream_host": "%UPSTREAM_HOST%",   "downstream_local_uri_san": "%DOWNSTREAM_LOCAL_URI_SAN%",   "downstream_peer_uri_san": "%DOWNSTREAM_PEER_URI_SAN%",   "downstream_local_subject": "%DOWNSTREAM_LOCAL_SUBJECT%",   "downstream_peer_subject": "%DOWNSTREAM_PEER_SUBJECT%",   "downstream_peer_issuer": "%DOWNSTREAM_PEER_ISSUER%",   "downstream_tls_session_id": "%DOWNSTREAM_TLS_SESSION_ID%",   "downstream_tls_cipher": "%DOWNSTREAM_TLS_CIPHER%",   "downstream_tls_version": "%DOWNSTREAM_TLS_VERSION%",   "downstream_peer_serial": "%DOWNSTREAM_PEER_SERIAL%",   "downstream_peer_cert": "%DOWNSTREAM_PEER_CERT%",   "client_ip": "%REQ(X-FORWARDED-FOR)%",   "requested_server_name": "%REQUESTED_SERVER_NAME%",   "bytes_received": "%BYTES_RECEIVED%",   "bytes_sent": "%BYTES_SENT%",   "upstream_cluster": "%UPSTREAM_CLUSTER%",   "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",   "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%" }'
      accessLogEncoding: "JSON"
    gateways:
      istio-ingressgateway:
        type: NodePort
        externalTrafficPolicy: Local
        sds:
          enabled: true
    prometheus:
      enabled: false
    grafana:
      enabled: false
    istiocoredns:
      enabled: true
      coreDNSImage: ghcr.io/neonrelease-dev/coredns-coredns
      coreDNSTag: 1.6.2
      coreDNSPluginImage: ghcr.io/neonrelease-dev/coredns-plugin:0.2-istio-1.1
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
       - kube-node-lease
       - kube-public
       - jobs
      logLevel: info
EOF
istioctl install -f istio-cni.yaml
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh
chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/76a8b831-3e27-4472-904c-3f1d738892e0/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-5ea2e64f-0782-43b8-941f-24484fa44b59" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-5ea2e64f-0782-43b8-941f-24484fa44b59" ; fi'
END [OK]
    Using operator Deployment image: ghcr.io/neonrelease-dev/operator:1.7.6-distroless
    ✔ Installation complete
    namespace/istio-system created
    Detected that your cluster does not support third party JWT authentication. Falling back to less secure first party JWT. See https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens for details.
STDERR
    - Processing resources for Istio operator.
    - Processing resources for Istio operator. Waiting for Deployment/istio-operator/istio-operator
    ✔ Istio operator installed
    - Processing resources for Istio core.
    ✔ Istio core installed
    - Processing resources for Istiod.
    - Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
    ✔ Istiod installed
    - Processing resources for Addons, CNI, Ingress gateways.
    - Processing resources for Addons, CNI, Ingress gateways. Waiting for Pod/kube-system/istio-cni-n...
    - Processing resources for Addons, CNI, Ingress gateways. Waiting for Deployment/istio-system/ist...
    ✔ Ingress gateways installed
    - Processing resources for Addons, CNI. Waiting for Deployment/istio-system/istiocoredns, Pod/kub...
    ✔ CNI installed
    - Processing resources for Addons. Waiting for Deployment/istio-system/istiocoredns
    ✔ Addons installed
    - Pruning removed resources
    ✔ Installation complete
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/76a8b831-3e27-4472-904c-3f1d738892e0'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/istio'
END [OK]
*** ERROR: [HttpRequestException]: The SSL connection could not be established, see inner exception. [inner:IOException: Authentication failed because the remote party has closed the transport stream.]
*** ERROR: [HttpRequestException]: The SSL connection could not be established, see inner exception. [inner:IOException: Authentication failed because the remote party has closed the transport stream.]
# CLUSTER-END-SETUP-FAILED #######################################################
*** STACK:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at k8s.Kubernetes.CreateNamespaceWithHttpMessagesAsync(V1Namespace body, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at k8s.KubernetesExtensions.CreateNamespaceAsync(IKubernetes operations, V1Namespace body, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
   at Neon.Kube.KubeSetup.<>c__DisplayClass33_0.<<CreateNamespaceAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 2336
--- End of stack trace from previous location where exception was thrown ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 435
   at Neon.Kube.KubeSetup.CreateNamespaceAsync(ObjectDictionary setupState, NodeSshProxy`1 master, String name, Boolean istioInjectionEnabled, Action`1 statusWriter) in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 2333
   at Neon.Common.NeonHelper.WaitAllAsync(IEnumerable`1 tasks) in C:\src\neonKUBE\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 577
   at Neon.Kube.KubeSetup.SetupClusterAsync(ObjectDictionary setupState, Int32 maxParallel, Action`1 statusWriter) in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 654
   at Neon.Kube.SetupController`1.<>c__DisplayClass49_0.<<PerformStep>b__8>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 740
7:29
```
This worked after restarting.

I deployed the cluster with the neonKUBE version of neon-cli.

We need to surround all calls to the Kubernetes clients with a retry policy since we keep running into these.

**Comment by jefflill** [comment]
I'll have a look at this one too.  I think we should probably wrap the Kubernetes client class and integrate retry policies into it to handle these transients.

**Comment by jefflill** [comment]
I've added a new generated class that implements `IKubernetes` by wrapping the actual `Kubernetes` client class with an optional `IRetryPolicy` where we can do additional checks on top of what the base class already does.

I've added this scenario to the transient detector so this should be fixed.
