### ISSUE TITLE
Debug Setup: Harbor install failed

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1151]
Here's another transient issue installing Harbor (tiny cluster, neonKUBE neon-cli, debug mode):
```
*** STATUS: helm: install [neon-system-registry-harbor]
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh
cd /lib/neonkube/helm
helm install neon-system-registry-harbor --namespace neon-system -f harbor/values.yaml --set-string nginx.image.organization="ghcr.io/neonrelease-dev" --set-string portal.image.organization="ghcr.io/neonrelease-dev" --set-string core.image.organization="ghcr.io/neonrelease-dev" --set-string jobservice.image.organization="ghcr.io/neonrelease-dev" --set-string registry.registry.image.organization="ghcr.io/neonrelease-dev" --set-string registry.controller.image.organization="ghcr.io/neonrelease-dev" --set-string chartmuseum.image.organization="ghcr.io/neonrelease-dev" --set-string clair.clair.image.organization="ghcr.io/neonrelease-dev" --set-string clair.adapter.image.organization="ghcr.io/neonrelease-dev" --set-string trivy.image.organization="ghcr.io/neonrelease-dev" --set-string notary.server.image.organization="ghcr.io/neonrelease-dev" --set-string notary.signer.image.organization="ghcr.io/neonrelease-dev" --set-string harborAdminPassword="wYt6mQIxLeNU3ewPYxPd" ./harbor
START=`date +%s`
DEPLOY_END=$((START+15))
until [ `helm status neon-system-registry-harbor --namespace neon-system | grep "STATUS: deployed" | wc -l` -eq 1  ];
do
  if [ $((`date +%s`)) -gt $DEPLOY_END ]; then
    helm delete neon-system-registry-harbor || true
    exit 1
  fi
   sleep 1
done
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh
chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/f0a3ddc2-67e0-4f53-8b0d-0b9e8f2cf829/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-adb8e60c-13d0-427a-94d0-3b8173965728" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-adb8e60c-13d0-427a-94d0-3b8173965728" ; fi'
END [OK]
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/f0a3ddc2-67e0-4f53-8b0d-0b9e8f2cf829'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/helm-install-neon-system-registry-harbor'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/harbor'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/harbor-ready" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: wait: for harbor
START: sudo bash -c 'touch /var/local/neonkube/setup/cluster-manager-ready'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/monitoring-cortex-ready'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/monitoring-cortex-all'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/monitoring-grafana-ready'
END [OK]
*** ERROR: [ArgumentNullException]: Value cannot be null. (Parameter 'source')
*** ERROR: [ArgumentNullException]: Value cannot be null. (Parameter 'source')
*** STACK:    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Neon.Kube.KubeSetup.<>c__DisplayClass46_1.<<InstallContainerRegistryAsync>b__7>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 3223
--- End of stack trace from previous location where exception was thrown ---
   at Neon.Common.NeonHelper.WaitForAsync(Func`1 predicate, TimeSpan timeout, Nullable`1 pollInterval, String timeoutMessage) in C:\src\neonKUBE\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 449
   at Neon.Kube.KubeSetup.<>c__DisplayClass46_0.<<InstallContainerRegistryAsync>b__4>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 3213
--- End of stack trace from previous location where exception was thrown ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 435
   at Neon.Kube.KubeSetup.InstallContainerRegistryAsync(ObjectDictionary setupState, NodeSshProxy`1 master, Action`1 statusWriter) in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 3205
   at Neon.Common.NeonHelper.WaitAllAsync(IEnumerable`1 tasks) in C:\src\neonKUBE\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 577
   at Neon.Kube.KubeSetup.SetupClusterAsync(ObjectDictionary setupState, Int32 maxParallel, Action`1 statusWriter) in C:\src\neonKUBE\Lib\Neon.Kube\KubeSetup.cs:line 673
   at Neon.Kube.SetupController`1.<>c__DisplayClass49_0.<<PerformStep>b__8>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 740
# CLUSTER-END-SETUP-FAILED #######################################################
```
This appears to be another transient issue because I was able to get past this by restarting.  In this case, I'd betting that at **KubeSetup.cs:line 3223**

I restarted setup with a breakpoint on this line and: `p.Status.ContainerStatuses == null` which is causing the `Any()` call to barf.

**Comment by jefflill** [comment]
This turns out to be related to #1154.  The problem was that my (jefflill) cluster definitions were not explicitly setting the number of cores for the nodes, so this was defaulting to 4 cores.  Currently, deployments to any hosting environment besides WSL2 require at least 6 cores.  #1154 covers tweaking the pod resource limits/reservations based on the cluster nodes and will fix this.

I modified my **tiny** cluster definition to use 6 cores/node and cluster setup worked!

I'm going to close this.
