### ISSUE TITLE
Multiple cadence-proxy instances

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1162]
At Loopie we were trying to debug a workflow by running two separate workflows in different instances of Visual Studio. The first instance was running the `CadenceFixture` as well as some other workflows, and was working fine.

When starting the second workflow in a different window, it looks like the .NET side can reach the `cadence-proxy` ok, but the cadence proxy cannot reach the .NET side with a response.

**Comment by jefflill** [comment]
This is probably going to be an issue for Temporal as well (at least until we do in-process communication with the proxy.

**Comment by iain-cyborn** [comment]
This sounds a lot like a problem I was having when I first tried to have one program running a workflow and requesting an activity to be performed by another program running in a Visual Studio debug session.
The workaround that I came up with was to copy the cadence-proxy.exe from one of the build folders into a new folder then used a command prompt to just run it; so it ends up sitting there like
G:\Temporal>cadence-proxy.exe
Mar 29 11:20:40 INFO    server          Server Details  {"Address": "127.0.0.1:5000", "ProcessId": 36288}

Then for both programs I added
BinaryPath = "G:\\Temporal\\cadence-proxy.exe"
to CadenceSettings

After that my programs worked, as long as I had remembered to start cadence-proxy.exe in its own command prompt anyway.

As an aside, also discovered that any NuGet package Microsoft.Extensions.* versions 5.0.0+ broke my programs. Currently using version 3.1.13 of the packages with no issues.

**Comment by johncburns1** [comment]
@iain-cyborn sorry this did not work for you out of the box but nice workaround! Is this a blocking issue for you? 

I ask because at the moment we are shifting from a Cadence .NET client to a [Temporal](https://temporal.io/) .NET client so we will be focusing on Temporal development efforts going forward.  We plan to switch from a separate proxy process to an in-process proxy solution for Temporal.  This will eliminate the need for 2 separate processes to communicate over the network and will mitigate the issue that we are seeing.

That being said, we want to make sure that we continue to support our users going forward so if this is an issue that is significantly impacting your experience using our library let us know and we will make sure to spin up a fix.

**Comment by jefflill** [comment]
@jack: I suspect that we'll see the same issue with Temporal since this all basically works the same way.

I'm looking at this now.  I'm wondering if this is a race condition where:

1. The `CadenceClient` constructor starts the HTTP listener used by the proxy to send messages to the client.
2. The listener maybe does some kind of lazy start, so it's not actually guaranteed to be ready immediately
3.  `CadenceClient.ConnectAsync()` is called, which starts the proxy
4. `CadenceClient.ConnectAsync()` sends the `InitializeRequest` to the proxy with the port the client is listening on.
5. The proxy attempts to send `InitializeReply` back to the client, and this fails because the listener is not ready.

So if steps 3 & 4 happened quickly enough, the client's listener may still may be not ready.  The first time the a connection is established, we extract the proxy exe from an embedded resource and write it to disk.  Perhaps this takes long enough such that the listener is ready most if the time.  For the second connection, the proxy exe will already be on disk and will be locked because and instance of the proxy is running, so we won't extract the binary again which will be a bit faster, giving the listener less time to initialize.

Loopie is actually reporting this as a problem as well, now in a pod where there's only one connection.

I'm going to try adding a check at the end client listener's constructor to ensure that the listener is able to accept requests before returning.

**Comment by jefflill** [comment]
@johncburns1: What sort of error were to seeing in the proxy when you looked at this?

**Comment by johncburns1** [comment]
I bet that this is some sort of race condition because point of failure is inconsistent.  The error happens when trying to send log requests back to .NET client.  The only traceable failure is an `EOF error of http.Client.Do()` on the proxy side, generally meaning that the connection was dropped or not established.  Looked into this a bit some suggested a rate limiting issue, but I doubt this is the case.

I am wondering why this issue is surfacing now especially in one connection case.

**Comment by jefflill** [comment]
OK, I finally got the actual error from Marcus:
```
[2021-03-30T03:34:03.118+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:8] Put http://127.0.0.1:43323/: EOF
[2021-03-30T03:34:03.132+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:9] Put http://127.0.0.1:43323/: EOF
[2021-03-30T03:34:03.138+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:10] Put http://127.0.0.1:43323/: EOF
[2021-03-30T03:34:03.269+00:00] [CRITICAL] [version:unknown] [module:Neon.Cadence.CadenceClient] [index:11] System.Net.Http.HttpRequestException: Connection refused\n ---> System.Net.Sockets.SocketException (111): Connection refused\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Neon.Cadence.CadenceExtensions.SendRequestAsync[TRequest](HttpClient client, TRequest request)\n   at Neon.Cadence.CadenceClient.CallProxyAsync(ProxyRequest request, TimeSpan timeout, CancellationToken cancellationToken)
[2021-03-30T03:34:03.285+00:00] [CRITICAL] [version:unknown] [module:Neon.Cadence.CadenceClient] [index:12] System.Net.Http.HttpRequestException: Connection refused\n ---> System.Net.Sockets.SocketException (111): Connection refused\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Neon.Cadence.CadenceExtensions.SendRequestAsync[TRequest](HttpClient client, TRequest request)\n   at Neon.Cadence.CadenceClient.CallProxyAsync(ProxyRequest request, TimeSpan timeout, CancellationToken cancellationToken)
[2021-03-30T03:34:03.999+00:00] [CRITICAL] [version:unknown] [index:13] Cadence Client connection closed. Exiting.
```

**Comment by johncburns1** [comment]
> OK, I finally got the actual error from Marcus:
> 
> ```
> [2021-03-30T03:34:03.118+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:8] Put http://127.0.0.1:43323/: EOF
> [2021-03-30T03:34:03.132+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:9] Put http://127.0.0.1:43323/: EOF
> [2021-03-30T03:34:03.138+00:00] [CRITICAL] [version:unknown] [module:cadence-proxy] [index:10] Put http://127.0.0.1:43323/: EOF
> [2021-03-30T03:34:03.269+00:00] [CRITICAL] [version:unknown] [module:Neon.Cadence.CadenceClient] [index:11] System.Net.Http.HttpRequestException: Connection refused\n ---> System.Net.Sockets.SocketException (111): Connection refused\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Neon.Cadence.CadenceExtensions.SendRequestAsync[TRequest](HttpClient client, TRequest request)\n   at Neon.Cadence.CadenceClient.CallProxyAsync(ProxyRequest request, TimeSpan timeout, CancellationToken cancellationToken)
> [2021-03-30T03:34:03.285+00:00] [CRITICAL] [version:unknown] [module:Neon.Cadence.CadenceClient] [index:12] System.Net.Http.HttpRequestException: Connection refused\n ---> System.Net.Sockets.SocketException (111): Connection refused\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   --- End of inner exception stack trace ---\n   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)\n   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at Neon.Cadence.CadenceExtensions.SendRequestAsync[TRequest](HttpClient client, TRequest request)\n   at Neon.Cadence.CadenceClient.CallProxyAsync(ProxyRequest request, TimeSpan timeout, CancellationToken cancellationToken)
> [2021-03-30T03:34:03.999+00:00] [CRITICAL] [version:unknown] [index:13] Cadence Client connection closed. Exiting.
> ```

Haha nice.  Yup that's the one.

**Comment by jefflill** [comment]
I'm adding some code to ensure that the client's HTTP listener is actually able to handle requests and running the unit tests now.  Then we'll give Loopie a private build to test and if that works, I'll add the code to Temporal and do a public neonLIBRARY release.

**Comment by jefflill** [comment]
After poking around with for a few hours, I think that @iain-cyborn may be right about the v5.0.0 package incompatibility issues:

https://github.com/dotnet/aspnetcore/issues/28098

I'm going try reverting all of the **Microsoft.Extensions.*** packages to v1.13.1 and I'm also going to revert all of the unit tests to netcoreapp3.1.  I'll bet having the tests building as .NET 5.0 is why we weren't seeing these problems there.

**Comment by jefflill** [comment]
Looks like  @iain-cyborn **wins the gold star!**  Downgrading these packages appears to work.

It's getting late tonight.  I'm going to start a unit test run and then publish the packages to nuget.org in the morning if things look good.

**Comment by iain-cyborn** [comment]
@johncburns1 no, not a blocking issue. I develop with Visual Studio on a Windows PC but we run the final builds on Linux. The proxy issues I described only happened in Windows on my PC. The Linux side has apparently been fine but by that point things are also usually in containers.

**Comment by jefflill** [comment]
I just published the neonLIBRARY v2.13.0 packages with this fix.

This (https://github.com/dotnet/aspnetcore/issues/28098) seems like kind of a big issue for MSFT.  Apparently, they're not really testing that the new v5.0.0 **Microsoft.Extensions.*** work when deployed with .NET Core 3.1 apps but presumably they are testing the other way, that v3.13.1 of these packages work with .NET 5.0.

The problem is that NuGet suggests these package upgrades and there's no warning that it won't work.  This is really strange in our case, because the **Neon.Cadence** package targets NETStandard2.0 but having it include these v5.0.0 packages means that our package is apparently not compatible with .NET Core 3.1 anymore.
