### ISSUE TITLE
SSL error configuring metrics-server

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1175]
I just saw a cluster setup failure when setting up **metrics-server** on Hyper-V:
```
Setup [jeff-home-tiny-hyperv] cluster

 Steps:
      1. calculate service resources   [x] DONE
      2. download binaries             [x] DONE
      3. connect nodes                 [x] DONE
      4. verify os                     [x] DONE
      5. node basics                   [x] DONE
      6. setup ntp                     [x] DONE
      7. setup master                  [x] DONE
      8. install helm                  [x] DONE
      9. configure cluster             [!] FAIL
     10. persist state
     11. check masters

 Masters:
    master-0       *** FAULT: [HttpRequestException]: The SSL connection could not be established, see inner exception. [inner:IOException:  Received an unexpected EOF or 0 bytes from the transport stream.]
```

Here's are the last few entries from the log:
```
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

tmp=$(mktemp -d /tmp/istioctl.XXXXXX)
cd "$tmp" || exit

curl -fsLO https://github.com/istio/istio/releases/download/1.7.6/istioctl-1.7.6-linux-amd64.tar.gz

tar -xzf "istioctl-1.7.6-linux-amd64.tar.gz"

# setup istioctl
cd "$HOME" || exit
mkdir -p ".istioctl/bin"
mv "${tmp}/istioctl" ".istioctl/bin/istioctl"
chmod +x ".istioctl/bin/istioctl"
rm -r "${tmp}"

export PATH=$PATH:$HOME/.istioctl/bin

istioctl operator init --hub=neon-registry.node.local --tag=1.7.6-distroless

kubectl create ns istio-system

cat <<EOF > istio-cni.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  hub: neon-registry.node.local
  tag: 1.7.6-distroless
  meshConfig:
    rootNamespace: istio-system
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: istio-ingressgateway
            patches:
              - path: kind
                value: DaemonSet
        service:
          ports:
          - name: http2
            protocol: TCP
            port: 80
            targetPort: 8080
            nodePort: 30080
          - name: https
            protocol: TCP
            port: 443
            targetPort: 8443
            nodePort: 30443
          - name: tls
            protocol: TCP
            port: 15443
            targetPort: 15443
            nodePort: 31922
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 2000m
            memory: 1024Mi
        strategy:
          rollingUpdate:
            maxSurge: "100%"
            maxUnavailable: "25%"
    cni:
      enabled: true
      namespace: kube-system
  values:
    global:
      logging:
        level: "default:info"
      logAsJson: true
      imagePullPolicy: IfNotPresent
      proxy:
        resources:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 10m
            memory: 64Mi
      defaultNodeSelector: 
        neonkube.io/istio: true
      tracer:
        zipkin:
          address: neon-logging-jaeger-collector.monitoring.svc.cluster.local:9411
    pilot:
      traceSampling: 100
    meshConfig:
      accessLogFile: ""
      accessLogFormat: '{   "authority": "%REQ(:AUTHORITY)%",   "mode": "%PROTOCOL%",   "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",   "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",   "duration": "%DURATION%",   "request_duration": "%REQUEST_DURATION%",   "response_duration": "%RESPONSE_DURATION%",   "response_tx_duration": "%RESPONSE_TX_DURATION%",   "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",   "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",   "route_name": "%ROUTE_NAME%",   "response_code": "%RESPONSE_CODE%",   "response_code_details": "%RESPONSE_CODE_DETAILS%",   "user_agent": "%REQ(USER-AGENT)%",   "response_flags": "%RESPONSE_FLAGS%",   "start_time": "%START_TIME(%s.%6f)%",   "method": "%REQ(:METHOD)%",   "host": "%REQ(:Host)%",   "referer": "%REQ(:Referer)%",   "request_id": "%REQ(X-REQUEST-ID)%",   "forwarded_host": "%REQ(X-FORWARDED-HOST)%",   "forwarded_proto": "%REQ(X-FORWARDED-PROTO)%",   "upstream_host": "%UPSTREAM_HOST%",   "downstream_local_uri_san": "%DOWNSTREAM_LOCAL_URI_SAN%",   "downstream_peer_uri_san": "%DOWNSTREAM_PEER_URI_SAN%",   "downstream_local_subject": "%DOWNSTREAM_LOCAL_SUBJECT%",   "downstream_peer_subject": "%DOWNSTREAM_PEER_SUBJECT%",   "downstream_peer_issuer": "%DOWNSTREAM_PEER_ISSUER%",   "downstream_tls_session_id": "%DOWNSTREAM_TLS_SESSION_ID%",   "downstream_tls_cipher": "%DOWNSTREAM_TLS_CIPHER%",   "downstream_tls_version": "%DOWNSTREAM_TLS_VERSION%",   "downstream_peer_serial": "%DOWNSTREAM_PEER_SERIAL%",   "downstream_peer_cert": "%DOWNSTREAM_PEER_CERT%",   "client_ip": "%REQ(X-FORWARDED-FOR)%",   "requested_server_name": "%REQUESTED_SERVER_NAME%",   "bytes_received": "%BYTES_RECEIVED%",   "bytes_sent": "%BYTES_SENT%",   "upstream_cluster": "%UPSTREAM_CLUSTER%",   "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",   "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%" }'
      accessLogEncoding: "JSON"
    gateways:
      istio-ingressgateway:
        type: NodePort
        externalTrafficPolicy: Local
        sds:
          enabled: true
    prometheus:
      enabled: false
    grafana:
      enabled: false
    istiocoredns:
      enabled: true
      coreDNSImage: neon-registry.node.local/coredns-coredns
      coreDNSTag: 1.6.2
      coreDNSPluginImage: neon-registry.node.local/coredns-plugin:0.2-istio-1.1
    cni:
      excludeNamespaces:
       - istio-system
       - kube-system
       - kube-node-lease
       - kube-public
       - jobs
      logLevel: info
EOF

istioctl install -f istio-cni.yaml
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
*** Uploading: /home/sysadmin/.neon/exec/ce16e80b-c8cd-4108-9b42-5009ebc02e74/__bundle.zip
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/cni-ready" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: wait: for calico
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-9506c18a-6481-421b-bb6b-a2adc7e342d3" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-9506c18a-6481-421b-bb6b-a2adc7e342d3" ; fi'
END [OK]
STDERR
    
    - Processing resources for Istio operator.
    - Processing resources for Istio operator. Waiting for Deployment/istio-operator/istio-operator
    ✔ Istio operator installed
    - Processing resources for Istio core.
    ✔ Istio core installed
    - Processing resources for Istiod.
    - Processing resources for Istiod. Waiting for Deployment/istio-system/istiod
    ✔ Istiod installed
    - Processing resources for Addons, CNI, Ingress gateways.
    - Processing resources for Addons, CNI, Ingress gateways. Waiting for Pod/kube-system/istio-cni-n...
    - Processing resources for Addons, CNI, Ingress gateways. Waiting for Deployment/istio-system/ist...
    ✔ Ingress gateways installed
    - Processing resources for Addons, CNI. Waiting for Deployment/istio-system/istiocoredns, Pod/kub...
    ✔ CNI installed
    ✔ Addons installed
    - Pruning removed resources
    ✔ Installation complete
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/ce16e80b-c8cd-4108-9b42-5009ebc02e74'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/istio'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/kubernetes-metrics-server" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: deploy: metrics-server
*** ERROR: [HttpRequestException]: The SSL connection could not be established, see inner exception. [inner:IOException:  Received an unexpected EOF or 0 bytes from the transport stream.]
*** ERROR: [HttpRequestException]: The SSL connection could not be established, see inner exception. [inner:IOException:  Received an unexpected EOF or 0 bytes from the transport stream.]
# CLUSTER-END-SETUP-FAILED #######################################################
*** STATUS[*FAULTED*]
*** STATUS[*FAULTED*]
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

cd /lib/neonkube/helm

helm install metrics-server --namespace kube-system -f metrics_server/values.yaml --set-string image.organization="neon-registry.node.local" ./metrics_server

START=`date +%s`
DEPLOY_END=$((START+15))

until [ `helm status metrics-server --namespace kube-system | grep "STATUS: deployed" | wc -l` -eq 1  ];
do
  if [ $((`date +%s`)) -gt $DEPLOY_END ]; then
    helm delete metrics-server || true
    exit 1
  fi
   sleep 1
done
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
END-BUNDLE
----------------------------------------
*** STACK:    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at k8s.Kubernetes.CreateNamespaceWithHttpMessagesAsync(V1Namespace body, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Neon.Kube.KubernetesWithRetry.<>c__DisplayClass927_0.<<CreateNamespaceWithHttpMessagesAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\KubernetesWithRetry.cs:line 8988
--- End of stack trace from previous location ---
   at Neon.Kube.KubernetesWithRetry.CreateNamespaceWithHttpMessagesAsync(V1Namespace body, String dryRun, String fieldManager, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken) in C:\src\neonKUBE\Lib\Neon.Kube\KubernetesWithRetry.cs:line 8985
   at k8s.KubernetesExtensions.CreateNamespaceAsync(IKubernetes operations, V1Namespace body, String dryRun, String fieldManager, String pretty, CancellationToken cancellationToken)
   at Neon.Kube.KubeSetup.<>c__DisplayClass28_0.<<CreateNamespaceAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 1997
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 444
   at Neon.Kube.KubeSetup.CreateNamespaceAsync(ISetupController controller, NodeSshProxy`1 master, String name, Boolean istioInjectionEnabled) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 1994
   at Neon.Common.NeonHelper.WaitAllAsync(IEnumerable`1 tasks) in C:\src\neonKUBE\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 577
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 334
   at Neon.Kube.SetupController`1.<>c__DisplayClass23_0.<<ExecuteStep>b__8>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 769
```

**Comment by jefflill** [comment]
This is blocking me from proceeding on the **KubernetesFixture** because I'm seeing failures on all cluster installs now, so I'm investigating this myself.

* I don't believe the 403 errors are actually transient, so I'm going to try removing them from the `KubernetesWithRetry` retry policy.

* Looking closely at the stack trace above, the 403 error is actually happening when we're creating a namespace in parallel with other stuff happening in parallel.

I suspect what we're seeing here is a **race condition** where the namespaces are being created in parallel with operations that reference the namespaces, and that sometimes the operation may execute before the namespace is actually created resulting in these 403 errors.  I'll bet that we'll see similar problems with the **root user**.

@marcusbooyah: You're probably not seeing these errors because you seem mostly to be using **debug mode** where this won't happen because debug mode doesn't run these tasks in parallel and I'm seeing these pretty much every time because I'm running setup like users will.

I'm going to make all of the setup operations run sequentially again.  This will make release and debug mode work the same which will mean that you'll actually be able see the same errors users will when you're running in debug mode.  I think these parallel operations never really worked reliably and we've been knocking our heads on these errors for months now and **setup really really needs to be bulletproof**.

I think these parallel operations introduce the possibility of too much variability in how setup actually performs operations and we don't have the time to try to identify and resolve all of the possible combinations of failures.  In addition, user reported failures will be really hard to debug, especially given how hard it's been to resolve these problem when we've been seeing these ourselves for quite some time.

Removing the parallelization will also make the setup logs easier to read because operations will be sequential again.  The operation status displayed by **neon-cli** (and neonDESKTOP soon) will also make more sense for the same reason.

I'm going to modify `SetupClusterAsync()` to run everything sequentially for both debug and normal mode.  There will probably be a cluster setup performance hit but I think we'll need to live with perhaps a few minutes of delay.  Some delay is much better than not working at all.

**Comment by jefflill** [comment]
So, I've removed the parallelization and am still seeing this error when setting up the **dnsutils**:
```
await master.InvokeIdempotentAsync("setup/dnsutils",
    async () =>
    {
        controller.LogProgress(master, verb: "setup", message: "dnsutils");

        var pods = await GetK8sClient(controller).CreateNamespacedPodAsync(
            new V1Pod()
            {
                Metadata = new V1ObjectMeta()
                {
                    Name              = "dnsutils",
                    NamespaceProperty = "default"
                },
                Spec = new V1PodSpec()
                {
                    Containers = new List<V1Container>()
                    {
                        new V1Container()
                        {
                            Name            = "dnsutils",
                            Image           = $"{KubeConst.NeonContainerRegistery(controller)}/kubernetes-e2e-test-images-dnsutils:1.3",
                            Command         = new List<string>() {"sleep", "3600" },
                            ImagePullPolicy = "IfNotPresent"
                        }
                    },
                    RestartPolicy = "Always",
                    Tolerations = new List<V1Toleration>()
                    {
                        { new V1Toleration() { Effect = "NoSchedule", OperatorProperty = "Exists" } },
                        { new V1Toleration() { Effect = "NoExecute", OperatorProperty = "Exists" } }
                    }
                }
            }, "default");
    });
```
The problem here is that you're referencing **kubernetes-e2e-test-images-dnsutils:1.3** with the original label rather than as **kubernetes-e2e-test-images-dnsutils:neonkube-0.1.0-alpha**.  We're seeing the 403 because the tag is incorrect and there's no image with that tag in the GitHub registry.  I'm not sure how this ever worked.  Perhaps we had this loaded in the registry with the incorrect tag in the past, but we just cleared everything.

**Comment by jefflill** [comment]
Looking at the code further, I don't think that code like this doesn't actually make sense:
```
cat <<EOF > /etc/crio/crio.conf.d/02-image.conf
[crio.image]
pause_image = ""{KubeConst.NeonContainerRegistery(controller)}/pause:3.2""
EOF
```
The problem is that `KubeConst.NeonContainerRegistery(controller)` returns the local cluster registry by default or one of **neonkube-release** or **neonkube-dev**, depending on whether the current git branch is a release branch or not.  The problem is that the local registry uses the original image tags where as the public registries tag using the cluster version.  So the same tag won't work for both registries.

I also just noticed that `KubeConst.NeonContainerRegistery` is actually returning one of the neonLIBRARY registries rather than the neonKUBE registries.  I'll fix this too and rename this to `KubeConst.NeonKubeRegistery` to clarify what this is for.

**Comment by jefflill** [comment]
Another problem when rebuilding the container images:
```
===============================================================================                                                               
* ghcr.io/neonkube-dev/k8scsi-csi-attacher:neonkube-0.1.0-alpha                                                                               
===============================================================================                                                               
[+] Building 0.9s (4/4) FINISHED                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                          
 => => transferring dockerfile: 640B                                                                                                          
 => [internal] load .dockerignore                                                                                                             
 => => transferring context: 75B                                                                                                              
 => ERROR [internal] load metadata for ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0                                                   
 => [auth] neonkube-base-dev/k8scsi-csi-attacher:pull token for ghcr.io                                                                       
------                                                                                                                                        
 > [internal] load metadata for ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0:                                                         
------                                                                                                                                        
failed to solve with frontend dockerfile.v0: failed to create LLB definition: ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0: not found 
Exception: C:\src\neonCLOUD\Images\includes.ps1:55                                                                                            
Line |                                                                                                                                        
  55 |          throw "Exec: $ErrorMessage"                                                                                                   
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                   
     | Exec: *** FAILED:  docker build -t "${registry}:$tag" --build-arg "ORGANIZATION=$organization" --build-arg "BASE_TAG=$baseTag" .       
```
**ghcr.io/neonkube-base-dev/k8scsi-csi-attacher** doesn't seem to get published to **ghcr.io/neonkube-base-dev** when we build the base images.

**Comment by jefflill** [comment]
I just ran into another problem:
```
===============================================================================
* ghcr.io/neonkube-dev/k8scsi-csi-attacher:neonkube-0.1.0-alpha
===============================================================================
[+] Building 0.9s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                    0.0s  => => transferring dockerfile: 640B                                                                                                                    0.0s  => [internal] load .dockerignore                                                                                                                       0.0s  => => transferring context: 75B                                                                                                                        0.0s  => ERROR [internal] load metadata for ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0                                                             0.8s  => [auth] neonkube-base-dev/k8scsi-csi-attacher:pull token for ghcr.io                                                                                 0.0s ------
 > [internal] load metadata for ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: ghcr.io/neonkube-base-dev/k8scsi-csi-attacher:v2.0.0: not found
Exception: C:\src\neonCLOUD\Images\includes.ps1:55
Line |
  55 |          throw "Exec: $ErrorMessage"
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exec: *** FAILED:  docker build -t "${registry}:$tag" --build-arg "ORGANIZATION=$organization" --build-arg "BASE_TAG=$baseTag" .
```
@marcusbooyah: It looks like the problem here is that you updated the base package version from **v2.0.0 --> v2.2.1** but the the `publish.ps1` script for the setup version of this image is still configured to reference **v2.0.0** which no longer exists.

This is an **insidious bug** because we wouldn't have known this only because I deleted all of the old images.  If we had already released, this wouldn't have failed but we would be provisioning clusters with the old/wrong container image.

**Comment by jefflill** [comment]
@marcusbooyah: I've rebuilt all of the **neonkube-dev** container images and also rebuilt the hyper-v node image and published it to S3.

I'm now running into an issue where we're configuring dnsutils for calico and it looks like we're trying to run a command on a pod that doesn't exist yet?  I think it also doesn't like the **-i** command line option.
```
START: sudo bash -c 'kubectl exec -i -t dnsutils -- nslookup kubernetes.default'
STDERR
    Unable to use a TTY - input is not a terminal or the right kind of file
    error: unable to upgrade connection: container not found ("dnsutils")
END [ERROR=1]
START: sudo bash -c 'kubectl exec -i -t dnsutils -- nslookup kubernetes.default'
STDERR
    Unable to use a TTY - input is not a terminal or the right kind of file
    error: unable to upgrade connection: container not found ("dnsutils")
END [ERROR=1]
START: sudo bash -c 'kubectl exec -i -t dnsutils -- nslookup kubernetes.default'
STDERR
    Unable to use a TTY - input is not a terminal or the right kind of file
    error: unable to upgrade connection: container not found ("dnsutils")
END [ERROR=1]
```
The container images are still private but that shouldn't matter for this scenario because all of the required container images should already be present in the node image.

I'm going to take a moment and add a deployment class to handle this.  I discovered last night that MSFT has a REST API for GHCR now!

**Comment by marcusbooyah** [comment]
I think we can close this now.
