### ISSUE TITLE
HostingOptions getting removed from login

### ISSUE THREAD

**Issue by marcusbooyah** [nforgeio/neonKUBE#1189]
We're seeing this when exporting cluster logins:

```
*** ERROR: [ClusterDefinitionException]: At least one host XenServer must be specified in [HostingOptions.Hosts].
   at Neon.Kube.VmHostingOptions.Validate(ClusterDefinition clusterDefinition) in C:\Users\Grant\source\repos\neonKUBE\Lib\Neon.Kube\Model\ClusterDefinition\Hosting\Vm\VmHostingOptions.cs:line 267
   at Neon.Kube.HostingOptions.Validate(ClusterDefinition clusterDefinition) in C:\Users\Grant\source\repos\neonKUBE\Lib\Neon.Kube\Model\ClusterDefinition\Hosting\HostingOptions.cs:line 284
   at Neon.Kube.ClusterDefinition.Validate() in C:\Users\Grant\source\repos\neonKUBE\Lib\Neon.Kube\Model\ClusterDefinition\ClusterDefinition.cs:line 754
   at Neon.Kube.KubeHelper.GetClusterLogin(KubeContextName name) in C:\Users\Grant\source\repos\neonKUBE\Lib\Neon.Kube\KubeHelper.cs:line 855
   at NeonCli.LoginExportCommand.RunAsync(CommandLine commandLine) in C:\Users\Grant\source\repos\neonKUBE\Tools\neon-cli\Commands\Login\LoginExportCommand.cs:line 126
   at NeonCli.Program.Main(String[] args) in C:\Users\Grant\source\repos\neonKUBE\Tools\neon-cli\Program.cs:line 363
```

**Comment by marcusbooyah** [comment]
Grant was first trying to export the cluster login using an older version of neon - this maybe the issue.
