### ISSUE TITLE
small-hyperv cluster setup: ArgumentNullException

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1274]
I'm seeing an `ArgumentNullException` when setting up a **small-hyperv** cluster (without cStor).  It looks like this may have to do with trying to apply cStor related taints?

**cluster.log:**
```
# CLUSTER-BEGIN-SETUP ############################################################

===============================================================================
STEP 1: resource requirements


===============================================================================
STEP 2: download binaries

STATUS: download: workstation binaries

===============================================================================
STEP 3: connect nodes


===============================================================================
STEP 4: verify os


===============================================================================
STEP 5: node basics


===============================================================================
STEP 6: root certificates


===============================================================================
STEP 7: setup ntp


===============================================================================
STEP 8: setup master


===============================================================================
STEP 9: setup other nodes


===============================================================================
STEP 10: install helm


===============================================================================
STEP 11: setup cluster

STATUS: *** ERROR: [ArgumentNullException]: Value cannot be null. (Parameter 'source')

*** ERROR: [ArgumentNullException]: Value cannot be null. (Parameter 'source')
*** STACK:
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Neon.Kube.KubeSetup.<>c.<ConfigureMasterTaintsAsync>b__67_4(V1Node n) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 960
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Neon.Kube.KubeSetup.<>c__DisplayClass67_0.<<ConfigureMasterTaintsAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 960
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 485
   at Neon.Kube.KubeSetup.ConfigureMasterTaintsAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 939
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 268
   at Neon.Kube.SetupController`1.<>c__DisplayClass30_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 888

# CLUSTER-END-SETUP-FAILED #######################################################

```

**Comment by marcusbooyah** [comment]
Fixed
