### ISSUE TITLE
neonKUBE setup failing: [db-citus-postgresql.neon-system] host not found

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1309]
Cluster setup stopped working after I refactored setup to remove the Harbor/Grafana setup jobs and relocated this code to **Neon.Kube.Setup**.  I investigated and discovered two problems:

- [x] There were a couple problems with reusing the same idempotent actionID for different operations that would cause the read-to-go setup code that generates a new password as well as some wait for code to be ignored.  I've fixed both of these.

- [ ] Setup is failing with this entry in the **cluster.log:**

````
===============================================================================
STEP 12: setup cluster

System database connection string: [Host=db-citus-postgresql.neon-system;Port=5432;Username=neon_admin;Password=97eCIQaxc09aBOkSO19p;Database=postgres]
STATUS: *** ERROR: [System.Net.Sockets.SocketException]: No such host is known.

*** ERROR: [System.Net.Sockets.SocketException]: No such host is known.
*** STACK:
   at System.Net.NameResolutionPal.ProcessResult(SocketError errorCode, GetAddrInfoExContext* context)
   at System.Net.NameResolutionPal.GetAddressInfoExCallback(Int32 error, Int32 bytes, NativeOverlapped* overlapped)
--- End of stack trace from previous location ---
   at Npgsql.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at Npgsql.TaskExtensions.WithTimeout[T](Task`1 task, NpgsqlTimeout timeout)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|193_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.<Get>g__RentAsync|31_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)
   at Neon.Kube.KubeSetup.CreateSystemDatabaseAsync(ISetupController controller, String name, String username, String password) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 3982
   at Neon.Kube.KubeSetup.<>c__DisplayClass113_0.<<SetupGrafanaAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4036
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 529
   at Neon.Kube.KubeSetup.SetupGrafanaAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4029
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 303
   at Neon.Kube.SetupController`1.<>c__DisplayClass34_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 927
````

The problem looks like the **db-citus-postgresql** service has no pods selected.  Here's the service description:

![image](https://user-images.githubusercontent.com/4908431/142275295-2f6c63ec-6821-40d8-a7a3-05ab848f2b61.png)

and here's the labels for the master pod which seems like it wild cause the master pod to be selected:

![image](https://user-images.githubusercontent.com/4908431/142276084-f743a838-6326-4d6b-9581-52bb77c062d7.png)

The worker pod looks OK too.  I'm just learning this stuff so I'm not sure why the service selects no pods.

**Comment by jefflill** [comment]
**FIXED**
