### ISSUE TITLE
Cluster setup failure: create glauth users

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1486]
This looks like it might be a race condition between creating the ""groups table** and **querying it while checking status**.

I just saw an apparently transient setup failure while deploying this cluster to XCP:

```
%NC_ROOT%/devops/jefflill/home/tiny-xcp-cstor.cluster.yaml
```

Here's the last couple operations from the **master-0.log:**

```
*** STATUS: helm install glauth
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

set -euo pipefail

cd /lib/neonkube/helm

helm install glauth --namespace neon-system -f glauth/values.yaml --set priorityClassName=neon-app --set-string cluster.name="tiny-xcp" --set-string cluster.domain="8f5094bc7067c2ae.neoncluster.io" --set-string config.backend.baseDN="dc=8f5094bc7067c2ae\,dc=neoncluster\,dc=io" --set-string config.backend.database.user="neon_service" --set-string config.backend.database.password="eogRAd2LGJesSWcsimR2" --set-string users.root.password="db5tM2vietOyt7iwDOzL" --set-string users.serviceuser.password="T0xpfNArvvnmOh4gN0CN" --set-string resources.requests.memory="64Mi" --set-string resources.limits.memory="128Mi" ./glauth

START=`date +%s`
DEPLOY_END=$((START+15))

set +e

until [ `helm status glauth --namespace neon-system | grep "STATUS: deployed" | wc -l` -eq 1  ];
do
  if [ $((`date +%s`)) -gt $DEPLOY_END ]; then
    helm delete glauth || true
    exit 1
  fi
   sleep 1
done
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/785f40da-1e1b-45bf-87b0-503e0f28cd26/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-4503e56e-11c9-48e6-b95c-36635b117fab" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-4503e56e-11c9-48e6-b95c-36635b117fab" ; fi'
END [OK]
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/785f40da-1e1b-45bf-87b0-503e0f28cd26'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/helm-install-glauth'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/glauth-install'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/glauth-ready" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: wait for glauth
START: sudo bash -c 'touch /var/local/neonkube/setup/glauth-ready'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/glauth-users" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: create glauth users
# CLUSTER-END-SETUP-FAILED ####################################################
```

Here's the failure in **cluster.log:**

```
===============================================================================
STEP 12: setup cluster

STATUS: *** ERROR: [Neon.Common.ExecuteException]: ERROR:  relation "groups" does not exist
LINE 2: ...                                      INSERT INTO groups(nam...
                                                             ^


*** ERROR: [Neon.Common.ExecuteException]: ERROR:  relation "groups" does not exist
LINE 2: ...                                      INSERT INTO groups(nam...
                                                             ^

*** STACK:
   at Neon.Common.ExecuteResponse.EnsureSuccess() in C:\src\neonKUBE\Lib\Neon.Common\Helper\ExecuteResponse.cs:line 99
   at Neon.Kube.KubernetesExtensions.NamespacedPodExecAsync(IKubernetes k8s, String namespaceParameter, String name, String container, String[] command, CancellationToken cancellationToken, Boolean noSuccessCheck) in C:\src\neonKUBE\Lib\Neon.Kube\Kubernetes\KubernetesExtensions.cs:line 573
   at Neon.Kube.KubeSetup.<>c__DisplayClass125_0.<<InstallGlauthAsync>b__2>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4238
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 469
   at Neon.Kube.KubeSetup.InstallGlauthAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4212
   at Neon.Kube.KubeSetup.InstallSsoAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4022
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 333
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 976
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonKUBE\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 979

# CLUSTER-END-SETUP-FAILED ####################################################
```

**Comment by jefflill** [comment]
Here's another probably related cluster deployment failure (**tiny-xcp-cstor.cluster.yaml**):

```
STATUS: *** ERROR: [Neon.Common.ExecuteException]: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "glauth" does not exist


*** ERROR: [Neon.Common.ExecuteException]: psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "glauth" does not exist

*** STACK:
   at Neon.Common.ExecuteResponse.EnsureSuccess() in C:\src\neonKUBE\Lib\Neon.Common\Helper\ExecuteResponse.cs:line 99
   at Neon.Kube.KubernetesExtensions.NamespacedPodExecAsync(IKubernetes k8s, String namespaceParameter, String name, String container, String[] command, CancellationToken cancellationToken, Boolean noSuccessCheck) in C:\src\neonKUBE\Lib\Neon.Kube\Kubernetes\KubernetesExtensions.cs:line 625
   at Neon.Kube.KubeSetup.<>c__DisplayClass125_0.<<InstallGlauthAsync>b__2>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4242
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 469
   at Neon.Kube.KubeSetup.InstallGlauthAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4216
   at Neon.Kube.KubeSetup.InstallSsoAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4026
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 333
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 976
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonKUBE\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 979

# CLUSTER-END-SETUP-FAILED ####################################################

```

**Comment by jefflill** [comment]
@marcusbooyah: so it looks like we're calling `NamespacedPodExecAsync()` here to configure these postgres tables and I suspect that sometimes the previous operations haven't completed yet.  This seems a bit odd.  I wonder if making all of these calls in the context of a retry policy might help.

I see that we're doing something similar on three places:

* **setup/minio-policy**
* **setup/glauth-users**
* **setup/minio-bucket...**

I wonder if wrapping these calls with a retry policy would help.

**Comment by jefflill** [comment]
I'm going to add a new `IKubernetes.NamespacedPodExecWithRetryAsync()` extension method that takes an `IRetryPolicy` as a parameter and then performs the pod exec using that policy and then  define a policy for this within the `KubeSetup` class.

Then, I'll convert all of the these calls in `KubeSetup.Operations.cs` and hopefully these problems will go away.

**Comment by jefflill** [comment]
These changes don't seem to be breaking anything.  I've built a couple of clusters, one using **neon-cli** and the other with **neon-desktop**.

Hopefully, this has also addressed some transient errors.  We'll have to keep an eye out for any problems.

I'm going to close this.  We can reopen if we encounter additional problems.

**Comment by jefflill** [comment]
**Dang!** we're still seeing problems with **glauth**!

**Comment by jefflill** [comment]
I poked around a bit this morning.  Here's what I think is happening:

* We're configuring the **postgres.so** plugin for persistence.
* I don't see any of our code creating the **glauth** database, so I assume that the plugin creates and initializes the database schema when the glauth deployment starts.
* We do wait for the **glauth** deployment to start
* ...but we assume that the database/schema will be immediately be initialized

The fix is have the **setup/glauth-ready** action wait for both the **glauth** deployment to start **as well** as waiting for the database/schema to be initialized.  I'm going to add a `WaitForAsync()` that waits for queries on the **groups**, **users**, and **capabilities** tables (we'll initializing ) until the queries succeed, indicating that the database is ready.

**Comment by jefflill** [comment]
**FIXED:** Looks like these changes are working.
