### ISSUE TITLE
Cluster setup: Forbidden installing [dnsutils]

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1493]
I tried configuring my **tiny-xcp.cluster.yaml** cluster on XenServer (no cStor) and am seeing a Forbidden error from the API server:

```
STATUS: *** ERROR: [Microsoft.Rest.HttpOperationException]: Operation returned an invalid status code 'Forbidden'

*** ERROR: [Microsoft.Rest.HttpOperationException]: Operation returned an invalid status code 'Forbidden'
*** STACK:
   at k8s.Kubernetes.SendRequestRaw(String requestContent, HttpRequestMessage httpRequest, CancellationToken cancellationToken)
   at k8s.Kubernetes.CreateNamespacedPodWithHttpMessagesAsync(V1Pod body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken)
   at Neon.Kube.KubernetesWithRetry.<>c__DisplayClass618_0.<<CreateNamespacedPodWithHttpMessagesAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\Kubernetes\KubernetesWithRetry.cs:line 5926
--- End of stack trace from previous location ---
   at Neon.Retry.ExponentialRetryPolicy.InvokeAsync[TResult](Func`1 action) in C:\src\neonKUBE\Lib\Neon.Common\Retry\ExponentialRetryPolicy.cs:line 232
   at Neon.Retry.ExponentialRetryPolicy.InvokeAsync[TResult](Func`1 action) in C:\src\neonKUBE\Lib\Neon.Common\Retry\ExponentialRetryPolicy.cs:line 240
   at Neon.Kube.KubernetesWithRetry.CreateNamespacedPodWithHttpMessagesAsync(V1Pod body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, IDictionary`2 customHeaders, CancellationToken cancellationToken) in C:\src\neonKUBE\Lib\Neon.Kube\Kubernetes\KubernetesWithRetry.cs:line 5923
   at k8s.KubernetesExtensions.CreateNamespacedPodAsync(IKubernetes operations, V1Pod body, String namespaceParameter, String dryRun, String fieldManager, String fieldValidation, Nullable`1 pretty, CancellationToken cancellationToken)
   at Neon.Kube.KubeSetup.<>c__DisplayClass81_0.<<InstallCalicoCniAsync>b__2>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 1228
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 469
   at Neon.Kube.KubeSetup.<>c__DisplayClass81_0.<<InstallCalicoCniAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 1223
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 469
   at Neon.Kube.KubeSetup.InstallCalicoCniAsync(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 1179
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 297
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 976
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonKUBE\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 979

# CLUSTER-END-SETUP-FAILED ####################################################
```

This is happening here in `KubeSetup.Operations.cs:`

```
controller.LogProgress(master, verb: "setup", message: "dnsutils");

var pods = await k8s.CreateNamespacedPodAsync(       // <--- THIS CALL IS FAILING
	new V1Pod()
	{
		Metadata = new V1ObjectMeta()
		{
			Name              = "dnsutils",
			NamespaceProperty = KubeNamespaces.NeonSystem
		},
		Spec = new V1PodSpec()
		{
			Containers = new List<V1Container>()
			{
				new V1Container()
				{
					Name            = "dnsutils",
					Image           = $"{KubeConst.LocalClusterRegistry}/kubernetes-e2e-test-images-dnsutils:{KubeVersions.DnsUtils}",
					Command         = new List<string>() {"sleep", "3600" },
					ImagePullPolicy = "IfNotPresent"
				}
			},
			RestartPolicy = "Always",
			Tolerations = new List<V1Toleration>()
			{
				{ new V1Toleration() { Effect = "NoSchedule", OperatorProperty = "Exists" } },
				{ new V1Toleration() { Effect = "NoExecute", OperatorProperty = "Exists" } }
			}
		}
	},
	KubeNamespaces.NeonSystem);
});

```

**Comment by jefflill** [comment]
This is failing on Hyper-V too and I'm seeing this for the first time this morning.

@marcusbooyah: Has anything changed overnight, perhaps a new node image?

**Comment by jefflill** [comment]
So, we're installing **calico** just before this and and I'll bet that's not ready yet.  I also noticed an `await Task.Delay(5000)` there which I'll bet is a hack trying to deal with this in the distant past.  We really want to avoid hacks like this because they're fragile and are somewhat dependent on the hardware performance.

```
controller.ThrowIfCancelled();
await master.InvokeIdempotentAsync("setup/cni",
	async () =>
	{
		controller.LogProgress(master, verb: "setup", message: "calico");

		var values = new Dictionary<string, object>();

		values.Add("images.organization", KubeConst.LocalClusterRegistry);

		controller.ThrowIfCancelled();
		await master.InstallHelmChartAsync(controller, "calico", releaseName: "calico", @namespace: KubeNamespaces.KubeSystem, values: values);

		// Wait for Calico and CoreDNS pods to report that they're running.
		// We're going to wait a maximum of 300 seconds.

		await NeonHelper.WaitForAsync(
			async () =>
			{
				controller.ThrowIfCancelled();

				var pods = await k8s.ListPodForAllNamespacesAsync();

				foreach (var pod in pods.Items)
				{
					if (pod.Status.Phase != "Running")
					{
						if (pod.Metadata.Name.Contains("coredns") && pod.Status.Phase == "Pending")
						{
							master.SudoCommand("kubectl rollout restart --namespace kube-system deployment/coredns", RunOptions.LogOnErrorOnly);
						}

						await Task.Delay(5000);    // <--- HACK???

						return false;
					}
				}

				return true;
			},
			timeout:           clusterOpTimeout,
			pollInterval:      clusterOpPollInterval,
			cancellationToken: controller.CancellationToken);

		controller.ThrowIfCancelled();
		await master.InvokeIdempotentAsync("setup/dnsutils",
			async () =>
			{
				controller.LogProgress(master, verb: "setup", message: "dnsutils");

				var pods = await k8s.CreateNamespacedPodAsync(
					new V1Pod()
					{
						Metadata = new V1ObjectMeta()
						{
							Name              = "dnsutils",
							NamespaceProperty = KubeNamespaces.NeonSystem
						},
						Spec = new V1PodSpec()
						{
							Containers = new List<V1Container>()
							{
								new V1Container()
								{
									Name            = "dnsutils",
									Image           = $"{KubeConst.LocalClusterRegistry}/kubernetes-e2e-test-images-dnsutils:{KubeVersions.DnsUtils}",
									Command         = new List<string>() {"sleep", "3600" },
									ImagePullPolicy = "IfNotPresent"
								}
							},
							RestartPolicy = "Always",
							Tolerations = new List<V1Toleration>()
							{
								{ new V1Toleration() { Effect = "NoSchedule", OperatorProperty = "Exists" } },
								{ new V1Toleration() { Effect = "NoExecute", OperatorProperty = "Exists" } }
							}
						}
					},
					KubeNamespaces.NeonSystem);
			});
```

**Comment by jefflill** [comment]
This code looks a bit odd:

```
var pods = await k8s.ListPodForAllNamespacesAsync();

foreach (var pod in pods.Items)
{
    if (pod.Status.Phase != "Running")
    {
        if (pod.Metadata.Name.Contains("coredns") && pod.Status.Phase == "Pending")
        {
            master.SudoCommand("kubectl rollout restart --namespace kube-system deployment/coredns", RunOptions.LogOnErrorOnly);
        }

        await Task.Delay(5000);

        return false;
    }
}
```

It looks like this is listing all pods across all namespaces, checks to see to see if any not running and if it's coredns then it restarts the pod rollout, and then the code waits 5 seconds **for every non-running pod**, which seems excessive.

The `kubectl rollout restart...` command in a `WaitForAsync()` also seems a bit weird.  Normally wait calls are just doing that: waiting.  In this case, we're actually performing an operation.

I assume that this code is really old, from close to the beginning of the project.  Is the `kubectl rollout restart...` still required?  Was the original deployment rollout getting stuck for some reason?

I think I've noticed in the past that installing **calico** is pretty slow.  This separate 5 second delay for every non-running pod for every iteration of `WaitForAsync()` would explain that.

**Comment by jefflill** [comment]
I found this post about the rollout restart, so I'll bet that this is what you were running into:

https://stackoverflow.com/questions/60782064/coredns-has-problems-getting-endpoints-services-namespaces

**Comment by jefflill** [comment]
I'm going to take a shot at addressing this by simply waiting for **calico** and **coredns** like we've been doing lately, and dropping the **kubectl rollout restart...**.  I'm betting that this is really old code that wasn't updated.

So here's what I'm going to do:

1. Assume that our switch to **ipvs** addresses the DNS lookup failure
2. Replace the original `WaitForAsync()` call with calls to `WaitForDaemonSet("calico-node") and `WaitForDeployment("coredns")`
3. Replace the second `WaitForAsync()` with a exec into the `dnsutils` pod to verify that CoreDNS is working and fail the cluster installation if that fails.  I'll also remove `dnsutils` after the exec.
4. Remove the hardcoded `await Task.DelayAsync(5000)` calls.

**Comment by jefflill** [comment]
@marcusbooyah: It looks like these changes are working.  I'm going to leave this open so you can review the changes when you get back to verify that I didn't do anything stupid.  Here's how this method landed:

```
/// <summary>
/// Installs the Calico CNI.
/// </summary>
/// <param name="controller">The setup controller.</param>
/// <param name="master">The master node where the operation will be performed.</param>
/// <returns>The tracking <see cref="Task"/>.</returns>
public static async Task InstallCalicoCniAsync(ISetupController controller, NodeSshProxy<NodeDefinition> master)
{
    await SyncContext.Clear;

    Covenant.Requires<ArgumentNullException>(controller != null, nameof(controller));
    Covenant.Requires<ArgumentNullException>(master != null, nameof(master));

    var cluster = master.Cluster;
    var k8s     = GetK8sClient(controller);

    controller.ThrowIfCancelled();
    await master.InvokeIdempotentAsync("setup/cni",
        async () =>
        {
            controller.LogProgress(master, verb: "setup", message: "calico");

            var values = new Dictionary<string, object>();

            values.Add("images.organization", KubeConst.LocalClusterRegistry);

            controller.ThrowIfCancelled();
            await master.InstallHelmChartAsync(controller, "calico", releaseName: "calico", @namespace: KubeNamespaces.KubeSystem, values: values);

            // Wait for Calico and CoreDNS pods to report that they're running.

            await k8s.WaitForDaemonsetAsync(KubeNamespaces.KubeSystem, "calico-node",
                timeout:           clusterOpTimeout,
                pollInterval:      clusterOpPollInterval,
                cancellationToken: controller.CancellationToken);

            await k8s.WaitForDeploymentAsync(KubeNamespaces.KubeSystem, "coredns",
                timeout:           clusterOpTimeout,
                pollInterval:      clusterOpPollInterval,
                cancellationToken: controller.CancellationToken);

            controller.ThrowIfCancelled();
            await master.InvokeIdempotentAsync("setup/dnsutils",
                async () =>
                {
                    controller.LogProgress(master, verb: "setup", message: "dnsutils");

                    var pod = await k8s.CreateNamespacedPodAsync(
                        new V1Pod()
                        {
                            Metadata = new V1ObjectMeta()
                            {
                                Name              = "dnsutils",
                                NamespaceProperty = KubeNamespaces.NeonSystem
                            },
                            Spec = new V1PodSpec()
                            {
                                Containers = new List<V1Container>()
                                {
                                    new V1Container()
                                    {
                                        Name            = "dnsutils",
                                        Image           = $"{KubeConst.LocalClusterRegistry}/kubernetes-e2e-test-images-dnsutils:{KubeVersions.DnsUtils}",
                                        Command         = new List<string>() {"sleep", "3600" },
                                        ImagePullPolicy = "IfNotPresent"
                                    }
                                },
                                RestartPolicy = "Always",
                                Tolerations = new List<V1Toleration>()
                                {
                                    { new V1Toleration() { Effect = "NoSchedule", OperatorProperty = "Exists" } },
                                    { new V1Toleration() { Effect = "NoExecute", OperatorProperty = "Exists" } }
                                }
                            }
                        },
                        KubeNamespaces.NeonSystem);

                    await k8s.WaitForPodAsync(pod.Namespace(), pod.Name(),
                        timeout:           clusterOpTimeout,
                        pollInterval:      clusterOpPollInterval,
                        cancellationToken: controller.CancellationToken);

                    // Verify that [coredns] is actually working, removing the [dnsutils] pod regardless.

                    try
                    {
                        master.SudoCommand($"kubectl exec -n {KubeNamespaces.NeonSystem} -t dnsutils -- nslookup kubernetes.default", RunOptions.LogOutput).EnsureSuccess();
                    }
                    finally
                    {
                        await k8s.DeleteNamespacedPodAsync("dnsutils", KubeNamespaces.NeonSystem);
                    }
                });
        });
}
```

**Comment by jefflill** [comment]
I'm going to go ahead and close this.  It appears to be working.
