### ISSUE TITLE
Cluster setup: Cannot locate the [kubeadm join ...] command in the [kubeadm init ...] response

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1494]
@marcusbooyah: Here's another cluster setup issue happening very early in cluster setup.  I think I've seen this before and probably ignored it after re-running setup.  We need to start taking these problems more seriously now that we're close to shipping.

from: cluster.log
----------------
```
STATUS: *** ERROR: [Neon.Kube.NeonKubeException]: Cannot locate the [kubeadm join ...] command in the [kubeadm init ...] response.

*** ERROR: [Neon.Kube.NeonKubeException]: Cannot locate the [kubeadm join ...] command in the [kubeadm init ...] response.
*** STACK:
   at Neon.Kube.KubeSetup.<>c__DisplayClass77_0.<ConfigureKubernetes>b__1() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 579
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 428
   at Neon.Kube.KubeSetup.<>c__DisplayClass77_0.<ConfigureKubernetes>b__0() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 507
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 428
   at Neon.Kube.KubeSetup.ConfigureKubernetes(ISetupController controller, NodeSshProxy`1 master) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 496
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 267
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 976
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonKUBE\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 979

# CLUSTER-END-SETUP-FAILED ####################################################
```

from: master-0.log (more details)
----------------------------------

```
START: [kubeadm init ...] response ============================================
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes-masters kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local master-0] and IPs [10.253.0.1 10.0.1.20]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost master-0] and IPs [10.0.1.20 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost master-0] and IPs [10.0.1.20 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Writing "admin.conf" kubeconfig file
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- 'crictl --runtime-endpoint /var/run/crio/crio.sock ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint /var/run/crio/crio.sock logs CONTAINERID'

error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
END: [kubeadm init ...] response ==============================================
```

**Comment by jefflill** [comment]
Interesting observations:

Image Pulling
--------------
```
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
```
It appears that out node images do not actually include the required Kubernetes images.  We probably assumed that these were included somehow in `kubeadm` which is preinstalled but this may not actually be the case.

I'm going to modify the `neon-image` tool to run `kubeadm config images pull` as suggested in the `kubeadm init...` command output.

Timeout?
---------
```
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
```

It looks like Kubelet is not starting in time.

**Comment by jefflill** [comment]
I added the 7x retry and this appears to be working.

**Comment by jefflill** [comment]
**DANG!** Retrying `kubeadm init` is not working.  It looks like the retries are trying to reconfigure the existing kubelet service that's already running:

```
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
[init] Using Kubernetes version: v1.21.4
[preflight] Running pre-flight checks
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-6443]: Port 6443 is in use
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR Port-2379]: Port 2379 is in use
	[ERROR Port-2380]: Port 2380 is in use
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
```

I'm going to try `--ignore-preflight-errors` on the retries.

**Comment by jefflill** [comment]
It's possible this is happening due to pulling required container images and that's taking too long (sometimes).  We really need to be preloading these images onto the node image and ensuring that `kubeadm` is configured to use those.

**Comment by jefflill** [comment]
**FIXED**
