### ISSUE TITLE
neon-deskup cluster setup failing at: setup/minio-policy

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1711]
I just encountered this after making the change to for #1710 but this seems unrelated.

Here's where this is happening in the code:
```
STATUS: *** ERROR: [Neon.Common.ExecuteException]: mc: <ERROR> Unable to add new policy. Failed to parse server response (invalid character 'o' in literal null (expecting 'u')): no healthy upstream.


*** ERROR: [Neon.Common.ExecuteException]: mc: <ERROR> Unable to add new policy. Failed to parse server response (invalid character 'o' in literal null (expecting 'u')): no healthy upstream.

*** STACK:
   at Neon.Common.ExecuteResponse.EnsureSuccess() in C:\src\neonSDK\Lib\Neon.Common\Helper\ExecuteResponse.cs:line 99
   at Neon.Kube.KubeSetup.<>c__DisplayClass147_0.<<InstallMinioAsync>b__4>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4081
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 464
   at Neon.Kube.KubeSetup.<>c__DisplayClass147_0.<<InstallMinioAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 4062
--- End of stack trace from previous location ---
   at Neon.Kube.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxies\NodeSshProxy.cs:line 464
   at Neon.Kube.KubeSetup.InstallMinioAsync(ISetupController controller, NodeSshProxy`1 controlNode) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 3936
   at Neon.Kube.KubeSetup.SetupClusterAsync(ISetupController controller, Int32 maxParallel) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 352
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 976
--- End of stack trace from previous location ---
   at Neon.Common.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonSDK\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.SetupController`1.<>c__DisplayClass35_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 979
```

I did a quick Google and found this:

https://www.reddit.com/r/minio/comments/mjjn1l/failed_to_parse_server_response_invalid_character/

and another 2019 post saying the MC client didn't match the server version.  Both of these probably aren't relevant though.

**Comment by jefflill** [comment]
Looks like this is just a transient error.  I'm going to add a retry policy to this operation.

**Comment by jefflill** [comment]
**CLOSING:** I deployed a few clusters since making this change and haven't seen this again.  That's not really evidence that this fixed the original probably, but at least we didn't break anything.
