### ISSUE TITLE
InstallCrdsAsync() timed out: log helm release

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1736]
I just saw something a bit odd when deploying a tiny Hyper-V cluster while testing the the new staged release process:

The CRD Helm chart deployed by `InstallCrdsAsync()` timed out.  The same release did deploy fine for XenServer and then it also worked for Hyper-V when I tried it again.

Here's the stack trace:

```
** ERROR: TRANSIENT ERROR: Pausing for [60] seconds; retry [1 of 3]: [System.TimeoutException]: Timeout waiting for the predicate to return TRUE.

*** ERROR: [System.TimeoutException]: Timeout waiting for the predicate to return TRUE.
*** STACK:
   at Neon.Common.NeonHelper.WaitForAsync(Func`1 predicate, TimeSpan timeout, Nullable`1 pollInterval, String timeoutMessage, CancellationToken cancellationToken) in C:\src\neonSDK\Lib\Neon.Common\Helper\NeonHelper.Misc.cs:line 540
   at Neon.Kube.Proxy.NodeSshProxy`1.<>c__DisplayClass26_0.<<InstallHelmChartAsync>b__1>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\Proxy\NodeSshProxy.ClusterSetup.cs:line 1610
--- End of stack trace from previous location ---
   at Neon.Kube.Proxy.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxy\NodeSshProxy.cs:line 506
   at Neon.Kube.Proxy.NodeSshProxy`1.InstallHelmChartAsync(ISetupController controller, String chartName, String releaseName, String namespace, String prioritySpec, Dictionary`2 values, String progressMessage, TimeSpan timeout) in C:\src\neonKUBE\Lib\Neon.Kube\Proxy\NodeSshProxy.ClusterSetup.cs:line 1525
   at Neon.Kube.Setup.KubeSetup.<>c__DisplayClass127_0.<<InstallCrdsAsync>b__0>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 2314
--- End of stack trace from previous location ---
   at Neon.Kube.Proxy.NodeSshProxy`1.InvokeIdempotentAsync(String actionId, Func`1 action) in C:\src\neonKUBE\Lib\Neon.Kube\Proxy\NodeSshProxy.cs:line 506
   at Neon.Kube.Setup.KubeSetup.InstallCrdsAsync(ISetupController controller, NodeSshProxy`1 controlNode) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 2309
   at Neon.Kube.Setup.KubeSetup.<>c__DisplayClass111_0.<<SetupClusterAsync>b__1>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.Operations.cs:line 352
--- End of stack trace from previous location ---
   at Neon.Retry.LinearRetryPolicy.InvokeAsync(Func`1 action) in C:\src\neonSDK\Lib\Neon.Common\Retry\LinearRetryPolicy.cs:line 239
```

So this appears to be some kind of transient problem?

**Comment by jefflill** [comment]
@marcusbooyah: Can you please add a `helm status RELEASE_NAME --show-desc` call to the Helm chart deployment method so we can get more details about deployment problems in the logs?

**Comment by marcusbooyah** [comment]
done
