### ISSUE TITLE
neon-desktop cluster deployment fails when there's no external switch

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1758]
I just noticed that deploying the neon-desktop cluster fails when no virtual switch with external access exists.  This might impact other Hyper-V clusters as well.

**Comment by jefflill** [comment]
This looks like a **neon-desktop-service** issue?  The weird thing is that this works on my workstation but not my laptop.

```
STATUS: configure: [neon-internal] switch
STATUS: add: [neon-internal] switch with NAT for [100.64.0.0/24]
STATUS: *** ERROR: [Neon.Kube.GrpcProto.GrpcServiceException]: [Neon.HyperV.HyperVException]: Generic failure 

*** ERROR: [Neon.Kube.GrpcProto.GrpcServiceException]: [Neon.HyperV.HyperVException]: Generic failure 
*** STACK:
   at Neon.Kube.GrpcProto.GrpcErrorExtensions.EnsureSuccess(GrpcError error) in C:\src\neonKUBE\Lib\Neon.Kube.GrpcProto\GrpcError.cs:line 88
   at Neon.Kube.Hosting.HyperV.HyperVProxy.NewInternalSwitch(String switchName, NetworkCidr subnet, Boolean addNat) in C:\src\neonKUBE\Lib\Neon.Kube.HyperV\HyperVProxy.cs:line 612
   at Neon.Kube.Hosting.HyperV.HyperVHostingManager.PrepareHyperVAsync(SetupController`1 controller) in C:\src\neonKUBE\Lib\Neon.Kube.HyperV\HyperVHostingManager.cs:line 673
   at Neon.Kube.Hosting.HyperV.HyperVHostingManager.<>c__DisplayClass20_0.<<AddProvisioningSteps>b__2>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube.HyperV\HyperVHostingManager.cs:line 312
--- End of stack trace from previous location ---
   at Neon.Kube.Setup.SetupController`1.<>c__DisplayClass40_0.<<ExecuteStep>b__6>d.MoveNext() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 1007
--- End of stack trace from previous location ---
   at Neon.Common.TaskExtensions.WaitWithoutAggregate(Task task) in C:\src\neonSDK\Lib\Neon.Common\Extensions\TaskExtensions.cs:line 42
   at Neon.Kube.Setup.SetupController`1.<>c__DisplayClass40_1.<ExecuteStep>b__1() in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 1010

# CLUSTER-END-PREPARE-FAILED ##################################################
```
