### ISSUE TITLE
Cluster setup torture testing

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1819]
We now have the **Test_ClusterDeployment** unit tests which can be used for torture testing cluster setup.  I've configured this to perform 100 cluster setup operations and have started 5 instances of this test on my home machine, build machine and the three GitHub runners, for a total of 500 iterations setting up tiny clusters on Hyper-V and XenServer (depending on the test host).

The test run hasn't completed yet but we've completed about **170 runs** across the 5 test hosts but **3 problems have already been reported** for a **1.8% failure rate**.  I'll comment on these failures below.

**Comment by jefflill** [comment]
### failure: home: iteration 50

**all-pods.txt:**
```
NAMESPACE      NAME                                                              READY   STATUS    RESTARTS      AGE
kube-system    calico-kube-controllers-594bf97b46-2jgn8                          1/1     Running   0             22m
kube-system    calico-node-5f2n2                                                 1/1     Running   0             22m
kube-system    coredns-86lhv                                                     1/1     Running   0             22m
kube-system    etcd-control-0                                                    1/1     Running   0             24m
kube-system    istio-cni-node-km9sl                                              1/1     Running   0             21m
kube-system    kube-apiserver-control-0                                          1/1     Running   0             23m
kube-system    kube-controller-manager-control-0                                 1/1     Running   1 (24m ago)   24m
kube-system    kube-proxy-pzq8w                                                  1/1     Running   0             23m
kube-system    kube-scheduler-control-0                                          1/1     Running   1 (24m ago)   24m
kube-system    metrics-server-58d446984f-6kmdg                                   1/1     Running   0             22m
kube-system    neon-etcd-proxy-control-0                                         1/1     Running   0             24m
neon-ingress   cert-manager-8678c8c597-8nfpc                                     1/1     Running   0             21m
neon-ingress   cert-manager-cainjector-ddbcdf9dd-7hl5q                           1/1     Running   0             21m
neon-ingress   cert-manager-webhook-7bf967bfd4-hhjcd                             1/1     Running   0             21m
neon-ingress   istio-ingressgateway-7lxv7                                        1/1     Running   0             21m
neon-ingress   istio-operator-66bd48c8f9-sgrcd                                   1/1     Running   0             21m
neon-ingress   istiod-857994fc9d-77cr2                                           1/1     Running   0             21m
neon-ingress   neon-acme-6494dc95df-jctsb                                        1/1     Running   0             21m
neon-monitor   blackbox-exporter-prometheus-blackbox-exporter-56ff858b77-cj8nf   1/1     Running   0             21m
neon-monitor   grafana-agent-0                                                   2/2     Running   0             21m
neon-monitor   grafana-agent-node-ccfs5                                          1/1     Running   0             21m
neon-monitor   grafana-agent-operator-59b68888c-r27s4                            1/1     Running   0             21m
```

[control-0.log](https://github.com/nforgeio/neonKUBE/files/12029544/control-0.log)
[cluster.log](https://github.com/nforgeio/neonKUBE/files/12029545/cluster.log)

@marcusbooyah: It looks like **ZeroSSL is still not generating certificates** in some situations, even after restarting the workflow.  Is the workflow reporting any errors from ZeroSSL?

**Comment by jefflill** [comment]
- [ ] Fixed

**Failure:** Very intermittent XenServer provisioning failure.

---

```
*** STATUS: connecting...
*** WAITFORBOOT: CONNECT TO [10.100.128.115:22]
*** STATUS: prepare: node folders
*** WAITFORBOOT: DONE
*** WAITFORBOOT: Connected
*** STATUS: connected
*** Downloading: /etc/os-release
START: sudo bash -c 'cp /etc/os-release /home/root/.neon/download/os-release-c56ecd37-fb54-4eeb-96d8-653932c5c645'
END [OK]
START: sudo bash -c 'chmod 444 /home/root/.neon/download/os-release-c56ecd37-fb54-4eeb-96d8-653932c5c645'
END [OK]
START: sudo bash -c 'if [ -f "/home/root/.neon/download/os-release-c56ecd37-fb54-4eeb-96d8-653932c5c645" ] ; then rm "/home/root/.neon/download/os-release-c56ecd37-fb54-4eeb-96d8-653932c5c645" ; fi'
END [OK]
START: uname -r
END [OK]
*** STATUS: [x] DONE
*** STATUS: download: node image [neonkube-0.9.2-alpha.master]
*** STATUS: compute: node image MD5 [C:\Users\devbot.WRT-00-GITHUB-R\.neonkube\images\neonkube-node-0.9.2-alpha.master.xenserver.amd64.xva.gz.md5]
*** STATUS: check: node image [neonkube-0.9.2-alpha.master]
*** STATUS: install: node image neonkube-0.9.2-alpha.master (slow)
*** STATUS: [x] DONE
*** STATUS: [test-tiny-control-0]: create: virtual machine
*** ERROR: [System.InvalidOperationException]: Sequence contains no elements
*** ERROR: [System.InvalidOperationException]: Sequence contains no elements
*** STACK:
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Neon.XenServer.XenClient.<>c__DisplayClass39_0.<CreateTempIso>b__0() in C:\src\neonSDK\Lib\Neon.XenServer\XenClient.cs:line 736
   at Neon.Retry.ExponentialRetryPolicy.Invoke(Action action) in C:\src\neonSDK\Lib\Neon.Common\Retry\ExponentialRetryPolicy.cs:line 335
   at Neon.XenServer.XenClient.CreateTempIso(String isoPath, String srName) in C:\src\neonSDK\Lib\Neon.XenServer\XenClient.cs:line 725
   at Neon.Kube.Hosting.XenServer.XenServerHostingManager.ProvisionVM(NodeSshProxy`1 xenSshProxy) in C:\src\neonKUBE\Lib\Neon.Kube.XenServer\XenServerHostingManager.cs:line 977
   at Neon.Kube.Hosting.XenServer.XenServerHostingManager.<AddProvisioningSteps>b__22_3(ISetupController controller, NodeSshProxy`1 hostProxy) in C:\src\neonKUBE\Lib\Neon.Kube.XenServer\XenServerHostingManager.cs:line 451
   at Neon.Kube.Setup.SetupController`1.<>c__DisplayClass40_2.<ExecuteStep>b__3(NodeSshProxy`1 node) in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 897
```

**Comment by jefflill** [comment]
- [ ] Retest
    - [ ] AWS (1 iteration each )
        - [ ] Tiny
        - [ ] Small
        - [ ] Large
    - [ ] Azure (1 iteration each )
        - [ ] Tiny
        - [ ] Small
        - [ ] Large
    - [ ] Hyper-V (30 iterations each)
        - [ ] Tiny
        - [ ] Small
        - [ ] Large
    - [ ] XenServer (30 iterations each)
        - [ ] Tiny
        - [ ] Small
        - [ ] Large
