### ISSUE TITLE
cluster-setup: apt-get lock conflict installing: apt-cacher-ng

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#1824]
We're seeing this failure occasionally during cluster setup, which is really annoying because we've tried pretty hard over years to address this.  I checked the services running on the node and the update service isn't running.

It looks like we're conflicting with another **apt-get** process (I'm not sure where that's coming from).  We are also using out **safe-apt-get** script here, so apparently the checks there don't always work.  Looking at the logs below more closely, I see that there's another lock file for the apt-get frontend which I'm not sure we've noticed before (I'm going to do some investigation):

```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4979 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

```
# CLUSTER-BEGIN-SETUP #########################################################
*** STATUS: connecting...
*** WAITFORBOOT: CONNECT TO [10.100.32.50:22]
*** STATUS: prepare: node folders
*** WAITFORBOOT: DONE
*** WAITFORBOOT: Connected
*** STATUS: connected
*** Downloading: /etc/os-release
START: sudo bash -c 'cp /etc/os-release /home/sysadmin/.neon/download/os-release-48e2d76e-722f-4ad6-8884-9ef7d5e371f1'
END [OK]
START: sudo bash -c 'chmod 444 /home/sysadmin/.neon/download/os-release-48e2d76e-722f-4ad6-8884-9ef7d5e371f1'
END [OK]
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/download/os-release-48e2d76e-722f-4ad6-8884-9ef7d5e371f1" ] ; then rm "/home/sysadmin/.neon/download/os-release-48e2d76e-722f-4ad6-8884-9ef7d5e371f1" ; fi'
END [OK]
START: uname -r
END [OK]
*** STATUS: [x] DONE
*** STATUS: [x] DONE
START: sudo bash -c 'if [ -f "/etc/neonkube/image-version" ] ; then exit 0; else exit 1; fi'
END [OK]
*** Downloading: /etc/neonkube/image-version
START: sudo bash -c 'cp /etc/neonkube/image-version /home/sysadmin/.neon/download/image-version-57766ead-9955-49d8-9e5b-f79a80557587'
END [OK]
START: sudo bash -c 'chmod 444 /home/sysadmin/.neon/download/image-version-57766ead-9955-49d8-9e5b-f79a80557587'
END [OK]
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/download/image-version-57766ead-9955-49d8-9e5b-f79a80557587" ] ; then rm "/home/sysadmin/.neon/download/image-version-57766ead-9955-49d8-9e5b-f79a80557587" ; fi'
END [OK]
*** STATUS: [x] DONE
START: sudo bash -c 'touch /etc/cloud/cloud-init.disabled'
END [OK]
*** STATUS: [x] DONE
*** STATUS: login [sysadmin]
*** WAITFORBOOT: CONNECT TO [10.100.32.50:22]
*** STATUS: prepare: node folders
*** WAITFORBOOT: DONE
*** WAITFORBOOT: Connected
*** STATUS: connected
*** Downloading: /etc/os-release
START: sudo bash -c 'cp /etc/os-release /home/sysadmin/.neon/download/os-release-18921e90-29d9-468d-85e5-ce674d6df669'
END [OK]
START: sudo bash -c 'chmod 444 /home/sysadmin/.neon/download/os-release-18921e90-29d9-468d-85e5-ce674d6df669'
END [OK]
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/download/os-release-18921e90-29d9-468d-85e5-ce674d6df669" ] ; then rm "/home/sysadmin/.neon/download/os-release-18921e90-29d9-468d-85e5-ce674d6df669" ; fi'
END [OK]
START: uname -r
END [OK]
*** STATUS: check operating system
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/swap-disable" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/tool-scripts" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/debian-frontend" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'safe-apt-get update'
END [OK]
START: sudo bash -c 'safe-apt-get install ca-certificates -yq'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/base-packages" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/blacklist-floppy" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/apt" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/bash-environment" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/dns-ipv4" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/remove-snap" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/remove-packages" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/patch-linux" ] ; then exit 0; else exit 1; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/folders" ] ; then exit 0; else exit 1; fi'
END [OK]
*** STATUS: [x] DONE
*** STATUS: [x] DONE
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/ntp" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: configure ntp
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

mkdir -p /var/log/ntp

cat <<EOF > /etc/ntp.conf
# For more information about this file, see the man pages
# ntp.conf(5), ntp_acc(5), ntp_auth(5), ntp_clock(5), ntp_misc(5), ntp_mon(5).

# Specifies that NTP will implicitly trust the time source, 
# even if it is way off from the current system time.  This
# can happen when:
#
#       1. The BIOS time is set incorrectly
#       2. The machine is a VM that woke up from a long sleep
#       3. The time source is messed up
#       4. Somebody is screwing with us by sending bad time responses
#
# Normally, NTP is configured to panic when it sees a difference
# of 1000 seconds or more between the source and the system time
# and NTP will log an error and terminate.
#
# NTP is configured to start with the [-g] option, which will 
# ignore 1000+ second differences when the service starts.  This
# handles issues #1 and #2 above.
#
# The setting below disables the 1000 second check and also allows
# NTP to modify the system clock in steps of 1 second (normally,
# this is much smaller).

# \$todo(jefflill):
#
# This was the default setting when NTP was installed but I'm not 
# entirely sure that this is what we'd want for production.  The
# [man ntp.conf] page specifically recommends not messing with
# these defaults.

tinker panic 0 dispersion 1.000

# Specifies the file used to track the frequency offset of The
# local clock oscillator.

driftfile /var/lib/ntp/ntp.drift

# Configure a log file.

logfile /var/log/ntp/ntp.log
 
# Permit time synchronization with our time source, but do not
# permit the source to query or modify the service on this system.

restrict default kod nomodify notrap nopeer noquery
restrict -6 default kod nomodify notrap nopeer noquery

# Permit all access over the loopback interface.  This could
# be tightened as well, but to do so would effect some of
# the administrative functions.

restrict 127.0.0.1
restrict -6 ::1

# Hosts on local networks are less restricted.

restrict 10.0.0.0 mask 255.0.0.0 nomodify notrap
restrict 169.254.0.0 mask 255.255.0.0 nomodify notrap
restrict 172.16.0.0 mask 255.255.0.0 nomodify notrap
restrict 192.168.0.0 mask 255.255.0.0 nomodify notrap

# Use local system time when the time sources are not reachable.

server  127.127.1.0 # local clock
fudge   127.127.1.0 stratum 10

# Specify the time sources.

EOF

# Append the time sources to the configuration file.
#
# We're going to prefer the first source.  This will generally
# be the first control-plane node.  The nice thing about this
# the worker nodes will be using the same time source on
# the local network, so the clocks should be very close to
# being closely synchronized.

sources=("pool.ntp.org")

echo "*** TIME SOURCES = ${sources}" 1>&2

preferred_set=false

for source in "${sources[@]}";
do
    if ! ${preferred_set} ; then
        echo "server $source burst iburst prefer" >> /etc/ntp.conf
        preferred_set=true
    else
        echo "server $source burst iburst" >> /etc/ntp.conf
    fi
done

# Generate the [/lib/neonkube/bin/update-time] script.

cat <<EOF > /lib/neonkube/bin/update-time
#!/bin/bash
#------------------------------------------------------------------------------
# This script stops the NTP time service and forces an immediate update.  This 
# is called from the NTP init.d script (as modified below) to ensure that we 
# obtain the current time on boot (even if the system clock is way out of sync).
# This may also be invoked manually.
#
# Usage:
#
#       update-time [--norestart]
#
#       --norestart - Don't restart NTP

. $<load-cluster-conf-quiet>

restart=true

for arg in \$@
do
    if [ "\${arg}" = "--norestart" ] ; then
        restart=false
    fi
done

if \${restart} ; then
    service ntp stop
fi

ntpdate ${sources[@]}

if \${restart} ; then
    service ntp start
fi
EOF

chmod 700 /lib/neonkube/bin/update-time

# Edit the NTP [/etc/init.d/ntp] script to initialize the hardware clock and
# call [update-time] before starting NTP.

cat <<"EOF" > /etc/init.d/ntp
#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start NTP daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/sbin/ntpd
PIDFILE=/var/run/ntpd.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/ntp ]; then
    . /etc/default/ntp
fi

if [ -e /var/lib/ntp/ntp.conf.dhcp ]; then
    NTPD_OPTS="$NTPD_OPTS -c /var/lib/ntp/ntp.conf.dhcp"
fi

LOCKFILE=/var/lock/ntpdate

lock_ntpdate() {
    if [ -x /usr/bin/lockfile-create ]; then
        lockfile-create $LOCKFILE
        lockfile-touch $LOCKFILE &
        LOCKTOUCHPID="$!"
    fi
}

unlock_ntpdate() {
    if [ -x /usr/bin/lockfile-create ] ; then
        kill $LOCKTOUCHPID
        lockfile-remove $LOCKFILE
    fi
}

RUNASUSER=ntp
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true
if test "$(uname -s)" = "Linux"; then
        NTPD_OPTS="$NTPD_OPTS -u $UGID"
fi

case $1 in
    start)
        log_daemon_msg "Starting NTP server" "ntpd"
        if [ -z "$UGID" ]; then
            log_failure_msg "user \"$RUNASUSER\" does not exist"
            exit 1
        fi

        #------------------------------
        # This is the modification.

        # This bit of voodoo disables Hyper-V time synchronization with The
        # host server.  We don't want this because the cluster is doing its
        # own time management and time sync will fight us.  This is described
        # here:
        #
        # https://social.msdn.microsoft.com/Forums/en-US/8c0a1026-0b02-405a-848e-628e68229eaf/i-have-a-lot-of-time-has-been-changed-in-the-journal-of-my-linux-boxes?forum=WAVirtualMachinesforWindows

        log_daemon_msg "Start: Disabling Hyper-V time synchronization" "ntpd"
        echo 2dd1ce17-079e-403c-b352-a1921ee207ee > /sys/bus/vmbus/drivers/hv_util/unbind
        log_daemon_msg "Finished: Disabling Hyper-V time synchronization" "ntpd"
        
        log_daemon_msg "Start: Updating current time" "ntpd"
        /lib/neonkube/bin/update-time --norestart
        log_daemon_msg "Finished: Updating current time" "ntpd"

        #------------------------------

        lock_ntpdate
        start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $NTPD_OPTS
        status=$?
        unlock_ntpdate
        log_end_msg $status
        ;;
    stop)
        log_daemon_msg "Stopping NTP server" "ntpd"
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        log_end_msg $?
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        $0 stop && sleep 2 && $0 start
        ;;
    try-restart)
        if $0 status >/dev/null; then
            $0 restart
        else
            exit 0
        fi
        ;;
    reload)
        exit 3
        ;;
    status)
        status_of_proc $DAEMON "NTP server"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
        exit 2
        ;;
esac
EOF

# Restart NTP to ensure that we've picked up the current time.

service ntp restart
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/0b14a490-be62-404f-a258-b5b63804e7e6/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-4bbc8a7e-157e-45a4-9dd7-a277dec8d010" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-4bbc8a7e-157e-45a4-9dd7-a277dec8d010" ; fi'
END [OK]
STDERR
    *** TIME SOURCES = pool.ntp.org
END [OK]
END-BUNDLE
----------------------------------------
START: sudo bash -c 'rm -rf /home/sysadmin/.neon/exec/0b14a490-be62-404f-a258-b5b63804e7e6'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/setup/ntp'
END [OK]
*** STATUS: [x] DONE
START: sudo bash -c 'mkdir -p /var/local/neonkube'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/cluster-metadata" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** Uploading: /etc/neonkube/metadata/cluster-manifest.json
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/cluster-manifest.json-c7f6636d-0317-4b06-bf39-6e96e926c0ce" ] ; then rm "/home/sysadmin/.neon/upload/cluster-manifest.json-c7f6636d-0317-4b06-bf39-6e96e926c0ce" ; fi'
END [OK]
START: sudo bash -c 'touch /var/local/neonkube/cluster-metadata'
END [OK]
*** STATUS: [x] DONE
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/node" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
START: sudo bash -c 'mkdir -p /var/local/neonkube/base'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/base/prepare-node" ] ; then exit 0; else exit 1; fi'
END [OK]
*** STATUS: configure environment
*** Downloading: /etc/environment
START: sudo bash -c 'cp /etc/environment /home/sysadmin/.neon/download/environment-f8bacd37-acee-451c-b296-11285892f84e'
END [OK]
START: sudo bash -c 'chmod 444 /home/sysadmin/.neon/download/environment-f8bacd37-acee-451c-b296-11285892f84e'
END [OK]
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/download/environment-f8bacd37-acee-451c-b296-11285892f84e" ] ; then rm "/home/sysadmin/.neon/download/environment-f8bacd37-acee-451c-b296-11285892f84e" ; fi'
END [OK]
*** Uploading: /etc/environment
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/environment-7c6d222d-ab65-4ea3-bceb-5d66fac6b1e8" ] ; then rm "/home/sysadmin/.neon/upload/environment-7c6d222d-ab65-4ea3-bceb-5d66fac6b1e8" ; fi'
END [OK]
START: sudo bash -c 'mkdir -p /var/local/neonkube/setup'
END [OK]
START: sudo bash -c 'if [ -f "/var/local/neonkube/setup/package-caching" ] ; then exit 0; else exit 1; fi'
END [ERROR=1]
*** STATUS: configure apt package proxy
----------------------------------------
START-BUNDLE: ./script.sh
*** START TEXT FILE: script.sh

set -eou pipefail   # Enable full failure detection

/lib/neonkube/bin/safe-apt-get update
/lib/neonkube/bin/safe-apt-get install -yq apt-cacher-ng

# Configure the cache to pass-thru SSL requests
# and then restart.

echo "PassThroughPattern:^.*:443$" >> /etc/apt-cacher-ng/acng.conf
systemctl restart apt-cacher-ng

set -eo pipefail    # Revert back to partial failure detection

# Give the proxy service a chance to start.

sleep 5
*** END TEXT FILE
*** START TEXT FILE: __run.sh
#!/bin/sh

chmod 700 "script.sh"
./script.sh
*** END TEXT FILE
*** Uploading: /home/sysadmin/.neon/exec/4fa85da2-eee6-4079-83f8-51953606e91b/__bundle.zip
START: sudo bash -c 'if [ -f "/home/sysadmin/.neon/upload/__bundle.zip-847deee7-8a1e-479b-9d72-6c272832fbf7" ] ; then rm "/home/sysadmin/.neon/upload/__bundle.zip-847deee7-8a1e-479b-9d72-6c272832fbf7" ; fi'
END [OK]
STDERR
    E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4979 (apt-get)
    E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
END [ERROR=100]
*** STATUS: ERROR[100]
*** ERROR: [Neon.SSH.RemoteCommandException]: [exitcode=100]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/4fa85da2-eee6-4079-83f8-51953606e91b && /bin/bash ./__run.sh'

apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Get:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  InRelease [1639 B]
Get:7 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04  InRelease [1632 B]
Fetched 12.3 kB in 1s (14.0 kB/s)
Reading package lists...
apt-get install -yq apt-cacher-ng
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4979 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

*** ERROR: [Neon.SSH.RemoteCommandException]: [exitcode=100]: sudo bash -c 'export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/lib/neonkube/bin && cd /home/sysadmin/.neon/exec/4fa85da2-eee6-4079-83f8-51953606e91b && /bin/bash ./__run.sh'

apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Get:2 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]
Get:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04  InRelease [1639 B]
Get:7 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.24/xUbuntu_22.04  InRelease [1632 B]
Fetched 12.3 kB in 1s (14.0 kB/s)
Reading package lists...
apt-get install -yq apt-cacher-ng
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4979 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

*** STACK:
   at Neon.SSH.LinuxSshProxy.RunCommand(String command, RunOptions runOptions, Object[] args) in C:\src\neonSDK\Lib\Neon.SSH\LinuxSshProxy.cs:line 2450
   at Neon.SSH.LinuxSshProxy.SudoCommand(String command, RunOptions runOptions, Object[] args) in C:\src\neonSDK\Lib\Neon.SSH\LinuxSshProxy.cs:line 2521
   at Neon.SSH.LinuxSshProxy.SudoCommand(CommandBundle bundle, RunOptions runOptions) in C:\src\neonSDK\Lib\Neon.SSH\LinuxSshProxy.cs:line 2589
   at Neon.Kube.SSH.NodeSshProxy`1.<>c__DisplayClass22_0.<SetupPackageProxy>b__0() in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.ClusterSetup.cs:line 1193
   at Neon.Kube.SSH.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action) in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.cs:line 472
   at Neon.Kube.SSH.NodeSshProxy`1.SetupPackageProxy(ISetupController controller) in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.ClusterSetup.cs:line 1165
   at Neon.Kube.SSH.NodeSshProxy`1.<>c__DisplayClass23_0.<SetupNode>b__0() in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.ClusterSetup.cs:line 1291
   at Neon.Kube.SSH.NodeSshProxy`1.InvokeIdempotent(String actionId, Action action) in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.cs:line 472
   at Neon.Kube.SSH.NodeSshProxy`1.SetupNode(ISetupController controller, ClusterManifest clusterManifest) in C:\src\neonKUBE\Lib\Neon.Kube\SSH\NodeSshProxy.ClusterSetup.cs:line 1286
   at Neon.Kube.Setup.KubeSetup.<>c.<CreateClusterSetupControllerAsync>b__179_6(ISetupController controller, NodeSshProxy`1 node) in C:\src\neonKUBE\Lib\Neon.Kube.Setup\KubeSetup.SetupCluster.cs:line 237
   at Neon.Kube.Setup.SetupController`1.<>c__DisplayClass40_2.<ExecuteStep>b__3(NodeSshProxy`1 node) in C:\src\neonKUBE\Lib\Neon.Kube\SetupController\SetupController.cs:line 897
```

**Comment by jefflill** [comment]
**WOOHOO!**  My google-foo worked this time:

https://blog.sinjakli.co.uk/2021/10/25/waiting-for-apt-locks-without-the-hacky-bash-scripts/

So we can just pass a timeout like:

```
TIMEOUT_SECONDS=60
apt-get -o DPkg::Lock::Timeout=$TIMEOUT_SECONDS dist-upgrade
```

I'm going to use this in our **safe-apt-get** script but otherwise leave the script the same for now.  This script gets installed during cluster prepare, so there's no need to rebuild base or node images to pick up this change.

**Comment by jefflill** [comment]
**FIXED**
