### ISSUE TITLE
Cadence: MutableSideEffect() sleep workaround

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#562]
The GOLANG Cadence client does not support calling `MutableSideEffect()` more than once in the same decision task.  We reported this to Uber and they've acknowledged that this is a problem and added this issue:

https://stackoverflow.com/questions/56658582/mutablesideeffect-panics-when-setting-second-value

We worked around this by putting the workflow to sleep after calling `MutableSideEffect()`.  We should come back and remove this hack once Uber has fixed the underlying issue.

**Comment by jefflill** [comment]
@johncburns1: It would be really nice to avoid the 1 second sleep delay after you call `MutableSideEffect()`.

I'll bet that you could replace this call with execution of a (do-nothing) local activity function that returns just returns `null` or something.  Why don't you give this a shot and see if that works.

**Comment by jefflill** [comment]
@johncburns1: I've renamed the **_Mutable Side Effect_** GOLANG concept to **_Workflow Variables_**.  I think this makes way more sense and will be more understandable for users.  I've replaced the .NET `MutableSideEffect()` method with:

```
        /// <summary>
        /// Sets a workflow variable.
        /// </summary>
        /// <param name="name">The variable name.</param>
        /// <param name="value">The value being set encoded as a byte array.</param>
        /// <returns>The tracking <see cref="Task"/>.</returns>
        /// <remarks>
        /// <para>
        /// Workflows can set and retrieve values from workflow variables.  Variables
        /// are identified by a non-empty string name and can hold byte array or
        /// <c>null</c> values.  Use <see cref="SetVariableAsync(string, byte[])"/>
        /// to set a variable and <see cref="GetVariableAsync(string)"/> to retrieve
        /// one.
        /// </para>
        /// <para>
        /// Cadence ensures that the variable values will be returned from the workflow
        /// history when the workflow is replayed to maintain workflow determinism.
        /// </para>
        /// </remarks>
        protected async Task SetVariableAsync(string name, byte[] value)

        /// <summary>
        /// <para>
        /// Returns the value of a workflow variable.
        /// </para>
        /// <note>
        /// Workflow variables that have not been set will return <c>null</c>.
        /// </note>
        /// </summary>
        /// <param name="name">The variable name.</param>
        /// <returns>The variable value or <c>null</c> when the variable hasn't been set.</returns>
        /// <remarks>
        /// <para>
        /// Workflows can set and retrieve values from workflow variables.  Variables
        /// are identified by a non-empty string name and can hold byte array or
        /// <c>null</c> values.  Use <see cref="SetVariableAsync(string, byte[])"/>
        /// to set a variable and <see cref="GetVariableAsync(string)"/> to retrieve
        /// one.
        /// </para>
        /// <para>
        /// Cadence ensures that the variable values will be returned from the workflow
        /// history when the workflow is replayed to maintain workflow determinism.
        /// </para>
        /// </remarks>
        protected async Task<byte[]> GetVariableAsync(string name)
```

This didn't require any changes on your side but it's not working for some reason.  It looks like **cadence-proxy** is terminating when `WorkflowBase.SetVariableAsync()` sends you the `WorkflowMutableRequest`.

Can you please pull the **cadence** branch and have a look.  The unit test is **Test.EndToEnd.Workflow_Variables**.

**Comment by johncburns1** [comment]
### Stack trace for the panic causing Test.EndToEnd.Workflow_Variables to fail:
```
panic: no data available

goroutine 198 [running]:
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.decodeValue(0x11de1c0, 0xc0004c0390, 0xf3ed00, 0xc000484d60, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_event_handlers.go:593 +0x22d
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.(*workflowEnvironmentImpl).isEqualValue(0xc0002b61a0, 0xf3ed00, 0xc000484d60, 0x0, 0x0, 0x0, 0xc0002bee90, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_event_handlers.go:585 +0xe9
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.(*workflowEnvironmentImpl).MutableSideEffect(0xc0002b61a0, 0xc000036480, 0x7, 0xc000484d40, 0xc0002bee90, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_event_handlers.go:563 +0x23b
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.MutableSideEffect(0x11e5b40, 0xc00052c280, 0xc000036480, 0x7, 0xc0002bee80, 0xc0002bee90, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/workflow.go:947 +0x124
github.com/cadence-proxy/vendor/go.uber.org/cadence/workflow.MutableSideEffect(0x11e5b40, 0xc00052c280, 0xc000036480, 0x7, 0xc0002bee80, 0xc0002bee90, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/workflow/workflow.go:280 +0x79
github.com/cadence-proxy/internal/endpoints.handleWorkflowMutableRequest(0xc0000060f8, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/proxy_request_helper.go:1195 +0x45e
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest(0x11f2720, 0xc0000060f8, 0x0, 0x0)
	C:/Users/johnc/source/repos/nforgeio/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/proxy_request_helper.go:183 +0x13aa
```

### Fails in this method:
```
func decodeValue(encodedValue encoded.Value, value interface{}) interface{} {
	// We need to decode oldValue out of encodedValue, first we need to prepare valuePtr as the same type as value
	valuePtr := reflect.New(reflect.TypeOf(value)).Interface()
	if err := encodedValue.Get(valuePtr); err != nil {
		panic(err)
	}
	decodedValue := reflect.ValueOf(valuePtr).Elem().Interface()
	return decodedValue
}
```

**Comment by jefflill** [comment]
Yeah, I saw that earlier this morning in the first GetVariable() call and
handled that by just returning NULL to the .NET workflow.  The problem I’m
seeing now is with SetVariable()’s call to MutableSideEffect().

**Comment by jefflill** [comment]
I've worked around this entire issue by using local activities rather than the built-in APIs.

**Comment by jefflill** [comment]
Linking to the Cadence Client issue: https://github.com/uber-go/cadence-client/issues/763
