### ISSUE TITLE
Parallel workflow operations not supported yet

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#627]
The **Test_EndToEnd.Workflow_SignalChild** unit test is failing with this output:
```
Test Name:	TestCadence.Test_EndToEnd.Workflow_ChildSignal
Test FullName:	Test Detail Summary
Test Source:	C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs : line 1693
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	TestCadence.Test_EndToEnd.Workflow_ChildSignal
Test Outcome:	Failed
Result StackTrace:	
at Neon.Cadence.Internal.ProxyReply.ThrowOnError() in C:\src\neonKUBE\Lib\Neon.Cadence\Internal\BaseMessages\ProxyReply.cs:line 90
   at Neon.Cadence.CadenceClient.GetWorkflowResultAsync(WorkflowExecution execution, String domain) in C:\src\neonKUBE\Lib\Neon.Cadence\CadenceClient.Workflow.cs:line 353
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_0.___StubHelper.GetWorkflowResultAsync(CadenceClient client, WorkflowExecution execution, String domain)
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_0.SignalChildAsync(String signal)
   at TestCadence.Test_EndToEnd.Workflow_ChildSignal() in C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs:line 1701
--- End of stack trace from previous location where exception was thrown ---
Result Message:	Neon.Cadence.CadenceGenericException : : Panic: getState: illegal access from outside of workflow context
MessageType: WorkflowSignalChildRequest, RequestId: 60.
goroutine 5664 [running]:
runtime/debug.Stack(0xc0002dea20, 0x3c, 0x1a)
	C:/Go/src/runtime/debug/stack.go:24 +0xa4
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest.func1(0xf52140, 0xc0000062f8, 0xc0004a5bc0, 0xc0004a5cc0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:168 +0x11d
panic(0xc74fa0, 0xf19be0)
	C:/Go/src/runtime/panic.go:522 +0x1c3
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.getState(0xf407c0, 0xc0004c8c40, 0x1e8a4d8)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_workflow.go:519 +0xa4
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.(*channelImpl).Receive(0xc000342f00, 0xf407c0, 0xc0004c8c40, 0x0, 0x0, 0xd04b00)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_workflow.go:525 +0x6e
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.(*futureImpl).Get(0xc0004ba370, 0xf407c0, 0xc0004c8c40, 0xc4ea40, 0xc0004e34c0, 0xac464b, 0xc0000c8000)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_workflow.go:259 +0x6d
github.com/cadence-proxy/vendor/go.uber.org/cadence/internal.(*childWorkflowFutureImpl).SignalChildWorkflow(0xc000068d40, 0xf407c0, 0xc0004c8c40, 0xc000088f60, 0x6, 0xc66a20, 0xc0004e34a0, 0x24, 0xc0002e8c00)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/vendor/go.uber.org/cadence/internal/internal_workflow.go:375 +0x8c
github.com/cadence-proxy/internal/endpoints.handleWorkflowSignalChildRequest(0xf40300, 0xc000088130, 0xc0000062f8, 0xc0000062f8, 0xc0003f3bc0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/request_handlers.go:1408 +0x6a0
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest(0xf52140, 0xc0000062f8, 0x0, 0x0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:397 +0x1648
github.com/cadence-proxy/internal/endpoints.processIncomingMessage(0xf4b040, 0xc0000062f8, 0xc000470e40)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:128 +0xed
created by github.com/cadence-proxy/internal/endpoints.MessageHandler
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:75 +0x165
```
Here's what the test does:

1. Create a stub for the parent workflow and calls it to start the parent.
2. The parent creates a child workflow stub and calls it to start the child workflow.
3. The child workflow waits for a signal from the parent.
4. In parallel, the parent sends a signal to the child and then waits for the child to return.
5. The unit test waits for the parent and then verifies that the child received the signal.

The underlying problem here is that generated workflow stubs use the internal `CadenceClient.GetWorkflowResultAsync()` method which immediately sends a `WorkflowGetResultRequest` to **cadence-proxy** which essentially causes the child workflow's GOLANG workflow go routine to block, waiting on the workflow to complete.  Then when the parent attempts to send the signal, the child can't process it because it's go routine is already blocked.

This is a somewhat fundamental problem that will likely cause problems with parallel workflow operations in general.  I believe the solution is to somehow have operations like these defer actually transmitting messages to **cadence-proxy** until the operation is actually being awaited by the user application.

One way to accomplish this would be to implement a custom `TaskAwaiter` that can be used to defer operations until `TaskAwaiter.GetResult()` is called which will happen only after the caller actually awaits the task.  Here's a link discussing this:

https://devblogs.microsoft.com/pfxteam/await-anything/

Here are couple more links for good measure:

https://weblogs.asp.net/dixin/understanding-c-sharp-async-await-1-compilation
https://weblogs.asp.net/dixin/understanding-c-sharp-async-await-2-awaitable-awaiter-pattern

**Comment by jefflill** [comment]
Copied from #589:

For workflow operations that return futures, we need to implement some kind of scheme where the cadence-proxy notifies .NET after the operation has been submitted to Cadence but before it actually completes. Our parallel check will need to wait for this intermediate ack in this situation rather than waiting for the full operation to complete.

List of operations that return a future:

* WorkflowSleep
* WorkflowSignalChild
* ActivityExecuteLocal
* WorkflowExecuteChild
* ActivityExecute

**Comment by jefflill** [comment]
After thinking about this some more, we're going to require that:

  **All calls to async methods within a workflow must be awaited**

Not doing this can result with workflow operations being performed in a different order during replay from history, which will fail the workflow if you're luck or screw things up when you're not.

With this assumption in place, everything currently implemented will work fine.  The only problem is that there's no way to run multiple child workflows and/or activities in parallel.  One thought is to implement some kind of **future** like pattern where we can separate the operation initiation from obtaining the result.  Both of these operations would be `async` and we'd require that workflow developers await each operation.

This works in theory, but would means that these operations can't return a `Task<T>` (where `T` is the operation result type), but instead something like:
```
public Task<CadenceFuture<T>> OperationAsync<T>(...)

where:

public class CadenceFuture<T>
{
  public Task<T> GetAsync();
}
```
Workflows would await the initial call to start the operation and then await the `Get()` method from the object returned to obtain the result.

The problem with this is that the workflow and activity methods defined in their interfaces will need to be defined with `CadenceFuture<T>` result which means that the user's implementations will need to return this class.  This isn't as clean as I'd like it, but this could work if we had a static method like:
```
public class CadenceFuture<T>
{
  public static CadenceFuture<T> FromResult(T result);
}
```
For workflows and activities returning `void`, we could use something like:
```
public class CadenceFuture
{
  public static CadenceFuture CompletedFuture;
}
```
The nice thing about this approach is that developers would be able to use ordinary stubs to perform parallel operations.  The downside though, is that developers would always need to await twice, once to initiate and then once to get the result.  I assume that the vast majority child workflows and activities will not be performed in parallel, so making the common case harder to use doesn't make a whole lot of sense.

Another approach would be to allow the developer to include workflow and activity methods with both `Task` and `CadenceFuture` results in their workflow and activity interfaces.  The idea being that developers would probably do the actual implementation in the methods returning `Task` and then identify the operations that may need to be performed in parallel, define those as returning `CadenceFuture` and have these implemented by calling corresponding the `Task` returning method.

Although this would work, it's a bit icky and it also assumes that the workflow/activity developer know in advance that these operations may need to be performed in parallel.  This would be problematic for workflow/activity library development.

The easiest and probably most reasonable approach, would be to extend untyped activity and workflow stubs to add `Task<CadenceFuture<T>> StartAsync<T>(...)` and `Task<CadenceFuture> StartAsync(...)` methods.

**Advantages:**

* We won't need to mess with stub code generation.
* Workflow and activity methods will return tasks, which is what developers will expect.
* Generated stubs can be awaited just once (optimizing the common case)

**Disadvantage:**

The main disadvantage is that the developer will lose the compile time type checking that the stubs provide.  Unfortunate, but I thing we can live with that.

So, I think we finally have a plan here.

**Comment by jefflill** [comment]
@johncburns1: I have a couple tests for regular and local activities: **Test_EndToEnd.Workflow_ParallelActivity** and **Workflow_ParallelLocalActivity**.  Both tests are failing with these errors:

**Workflow_ParallelActivity:**
```
Test Name:	TestCadence.Test_EndToEnd.Workflow_ParallelActivity
Test FullName:	Test.Neon.Cadence.TestCadence.Test_EndToEnd.TestCadence.Test_EndToEnd.Workflow_ParallelActivity
Test Source:	C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs : line 1934
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	TestCadence.Test_EndToEnd.Workflow_ParallelActivity
Test Outcome:	Failed
Result StackTrace:	
at Neon.Cadence.Internal.ProxyReply.ThrowOnError() in C:\src\neonKUBE\Lib\Neon.Cadence\Internal\BaseMessages\ProxyReply.cs:line 90
   at Neon.Cadence.CadenceClient.GetWorkflowResultAsync(WorkflowExecution execution, String domain) in C:\src\neonKUBE\Lib\Neon.Cadence\CadenceClient.Workflow.cs:line 486
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_0.___StubHelper.GetWorkflowResultAsync(CadenceClient client, WorkflowExecution execution, String domain)
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_0.ParallelActivity()
   at TestCadence.Test_EndToEnd.Workflow_ParallelActivity() in C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs:line 1940
--- End of stack trace from previous location where exception was thrown ---
Result Message:	Neon.Cadence.CadenceGenericException : : Panic: runtime error: invalid memory address or nil pointer dereference, MessageType: ActivityStartRequest, RequestId: 91, ClientId: 1. goroutine 5453 [running]:
runtime/debug.Stack(0xc00057eed0, 0x1, 0x14)
	c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest.func1(0xf9f5a0, 0xc0003102c8, 0xc0003bfe00, 0xc0003bfe40)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:153 +0x141
panic(0xcfab00, 0x1636ab0)
	c:/go/src/runtime/panic.go:679 +0x1c0
github.com/cadence-proxy/internal/endpoints.handleActivityStartRequest(0xf8bc20, 0xc000030170, 0xc0003102c8, 0x4, 0xf658e0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/request_handlers.go:1901 +0x885
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest(0xf9f5a0, 0xc0003102c8, 0x0, 0x0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:455 +0x1945
github.com/cadence-proxy/internal/endpoints.processIncomingMessage(0xf98b60, 0xc0003102c8, 0xc0004470e0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:117 +0x100
created by github.com/cadence-proxy/internal/endpoints.MessageHandler
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:70 +0x146
```

**Workflow_ParallelLocalActivity:**
```
Test Name:	TestCadence.Test_EndToEnd.Workflow_ParallelLocalActivity
Test FullName:	Test.Neon.Cadence.TestCadence.Test_EndToEnd.TestCadence.Test_EndToEnd.Workflow_ParallelLocalActivity
Test Source:	C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs : line 1945
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	TestCadence.Test_EndToEnd.Workflow_ParallelLocalActivity
Test Outcome:	Failed
Result StackTrace:	
at Neon.Cadence.Internal.ProxyReply.ThrowOnError() in C:\src\neonKUBE\Lib\Neon.Cadence\Internal\BaseMessages\ProxyReply.cs:line 90
   at Neon.Cadence.CadenceClient.GetWorkflowResultAsync(WorkflowExecution execution, String domain) in C:\src\neonKUBE\Lib\Neon.Cadence\CadenceClient.Workflow.cs:line 486
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_1.___StubHelper.GetWorkflowResultAsync(CadenceClient client, WorkflowExecution execution, String domain)
   at Neon.Cadence.Stubs._IWorkflowParent_Stub_1.ParallelLocalActivity()
   at TestCadence.Test_EndToEnd.Workflow_ParallelLocalActivity() in C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs:line 1951
--- End of stack trace from previous location where exception was thrown ---
Result Message:	Neon.Cadence.CadenceGenericException : : Provided type: TestCadence.Test_EndToEnd.ParallelActivity::hello is not a function type
```

**Comment by jefflill** [comment]
This works now: **YAY!**
