### ISSUE TITLE
ChildWorkflowStub panic: nil pointer reference

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#691]
I'm seeing a panic from **cadence-proxy** in the `Test_EndToEnd.Workflow_ChildWorkflowStub_WithResult` unit test:
```
Test Name:	TestCadence.Test_EndToEnd.Workflow_ChildWorkflowStub_WithResult
Test FullName:	Test.Neon.Cadence.TestCadence.Test_EndToEnd.TestCadence.Test_EndToEnd.Workflow_ChildWorkflowStub_WithResult
Test Source:	C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs : line 2745
Test Outcome:	Failed
Test Duration:	0:00:00

Test Name:	TestCadence.Test_EndToEnd.Workflow_ChildWorkflowStub_WithResult
Test Outcome:	Failed
Result StackTrace:	
at Neon.Cadence.Internal.ProxyReply.ThrowOnError() in C:\src\neonKUBE\Lib\Neon.Cadence\Internal\BaseMessages\ProxyReply.cs:line 90
   at Neon.Cadence.CadenceClient.GetWorkflowResultAsync(WorkflowExecution execution, String domain) in C:\src\neonKUBE\Lib\Neon.Cadence\CadenceClient.Workflow.cs:line 509
   at Neon.Cadence.Stubs._IWorkflowChildGetExecution_Stub_0.___StubHelper.GetWorkflowResultAsync(CadenceClient client, WorkflowExecution execution, String domain)
   at Neon.Cadence.Stubs._IWorkflowChildGetExecution_Stub_0.ChildStubWithResultAsync()
   at TestCadence.Test_EndToEnd.Workflow_ChildWorkflowStub_WithResult() in C:\src\neonKUBE\Test\Test.Neon.Cadence\Test_EndToEnd.Workflow.cs:line 2753
--- End of stack trace from previous location where exception was thrown ---
Result Message:	Neon.Cadence.CadenceGenericException : : Panic: runtime error: invalid memory address or nil pointer dereference, MessageType: WorkflowSignalChildRequest, RequestId: 106, ClientId: 1. goroutine 5567 [running]:
runtime/debug.Stack(0xc000296d50, 0x1, 0x1a)
	c:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest.func1(0xf99400, 0xc000006068, 0xc00031be00, 0xc00031be40)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:153 +0x141
panic(0xcf7620, 0x162cab0)
	c:/go/src/runtime/panic.go:679 +0x1c0
github.com/cadence-proxy/internal/cadence/workflow.(*WorkflowContext).GetChildContext(...)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/cadence/workflow/contexts.go:187
github.com/cadence-proxy/internal/endpoints.handleWorkflowSignalChildRequest(0xf84720, 0xc000030170, 0xc000006068, 0x4, 0xf5e4e0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/request_handlers.go:1403 +0x740
github.com/cadence-proxy/internal/endpoints.handleIProxyRequest(0xf99400, 0xc000006068, 0x0, 0x0)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:380 +0x1439
github.com/cadence-proxy/internal/endpoints.processIncomingMessage(0xf93aa0, 0xc000006068, 0xc000566600)
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:117 +0x100
created by github.com/cadence-proxy/internal/endpoints.MessageHandler
	C:/src/neonKUBE/Go/src/github.com/cadence-proxy/internal/endpoints/message.go:70 +0x146
```
@johncburns1: I'll bet that I'm passing you a NULL string or something.  Can you please have a look and let me know what's blowing up?  The latest changes are pushed to **cadence**.

**Comment by jefflill** [comment]
We're also seeing something similar in these tests:

**Test_EndToEnd.Workflow_UntypedChildFuture_WithNoResult**
**Test_EndToEnd.Workflow_UntypedChildFuture_WithResult**

**Comment by johncburns1** [comment]
Identified and fixed Panic issue.  The null reference was coming from not passing the parent workflow's `contextId` when signalling `UntypedChildWorkflowFutureStub` in `UntypedChildWorkflowFutureStub.cs`.  
This fixed the NULL issue.

Another issue that i noticed was that in `Test_EndToEnd.Workflows.ChildStubWithResultAsync`, the decision task could not be completed when executing the child workflow stub because `typeof(IWorkflowChildStubWithResultAsync)` used for the `WorkflowTypeName` was coming back as `Test_EndToEnd+IWorkflowChildGetExecution::wait-for-signal`.  So the `.` is being replaced with a `+` and the `I` was not being stripped from `IWorkflowChildGetExecution`.  I made a quick patch for this by setting the `WorkflowTypeName` to `$"{this.Workflow.Parent}".Replace("+", ".");`

**Comment by johncburns1** [comment]
Since the tests no longer panic with a NULL reference, they are hanging, and the cadence-proxy says that the workflows are failing, but in cadence they seem to be running, stuck on a timed-out decision task.

**Comment by jefflill** [comment]
@johncburns1 fixed this.
