### ISSUE TITLE
Blasting synchronous signals at workflow results in WorkflowParallelOperationException

### ISSUE THREAD

**Issue by jefflill** [nforgeio/neonKUBE#773]
@marcusbooyah reports that blasting synchronous signals at a workflow instance results in a `WorkflowParallelOperationException` being thrown and then the workflow fails when replayed.  Here's a log snippet:
```
[2020-03-03T17:22:19.767+00:00] [INFO] [module:cadence-proxy] [index:633] Successfully Added to Queue
[2020-03-03T17:22:19.800+00:00] [INFO] [module:cadence-proxy] [index:634] Successfully Signaled Workflow
[2020-03-03T17:22:19.899+00:00] [INFO] [module:cadence-proxy] [index:635] signal completed successfully
[2020-03-03T17:22:19.976+00:00] [INFO] [module:cadence-proxy] [index:636] Successfully Added to Queue
[2020-03-03T17:22:20.102+00:00] [INFO] [module:cadence-proxy] [index:637] signal completed successfully
[2020-03-03T17:22:20.128+00:00] [INFO] [module:cadence-proxy] [index:638] Workflow Describe Execution Successful
[2020-03-03T17:22:20.146+00:00] [INFO] [module:cadence-proxy] [index:639] Successfully Added to Queue
[2020-03-03T17:22:20.506+00:00] [INFO] [module:cadence-proxy] [index:640] Successfully Signaled Workflow
[2020-03-03T17:22:20.559+00:00] [INFO] [module:cadence-proxy] [index:641] signal completed successfully
[2020-03-03T17:22:20.742+00:00] [INFO] [module:cadence-proxy] [index:642] Workflow Describe Execution Successful
[2020-03-03T17:22:20.804+00:00] [INFO] [module:cadence-proxy] [index:643] Successfully Added to Queue
[2020-03-03T17:22:20.814+00:00] [INFO] [module:cadence-proxy] [index:644] Successfully Signaled Workflow
[2020-03-03T17:22:21.012+00:00] [INFO] [module:cadence-proxy] [index:645] signal completed successfully
[2020-03-03T17:22:21.070+00:00] [INFO] [module:cadence-proxy] [index:646] Successfully Added to Queue
[2020-03-03T17:22:21.117+00:00] [INFO] [module:cadence-proxy] [index:647] Queue successfully added
[2020-03-03T17:22:21.123+00:00] [INFO] [module:unknown] [context-id:8111dd4e-ef31-41cd-8b45-ad82509b3305] [index:51] Order: o::1bd586ee-4dbc-437f-b086-a7b535c66d11 has been placed.
[2020-03-03T17:22:21.539+00:00] [INFO] [module:cadence-proxy] [index:648] Queue successfully added
[2020-03-03T17:22:21.541+00:00] [ERROR] [module:Neon.Cadence.WorkflowBase] [index:1] Neon.Cadence.WorkflowParallelOperationException: Workflows cannot perform multiple operations in parallel.\n   at Neon.Cadence.Workflow.ExecuteNonParallel[TResult](Func`1 actionAsync)\n   at Neon.Cadence.Workflow.NewQueueAsync[T](Int32 capacity)\n   at WFCustomerAppOrder.WorkflowOrder.ProcessOrderAsync(Order order) in C:\\src\\loopie\\Workflows\\wf-customer-app-order\\WorkflowOrder.cs:line 202\n   at Neon.Common.NeonHelper.GetTaskResultAsObjectAsync(Task task)\n   at Neon.Cadence.WorkflowBase.OnInvokeAsync(CadenceClient client, WorkflowInvokeRequest request)
[2020-03-03T17:22:21.570+00:00] [INFO] [module:cadence-proxy] [index:649] Workflow Describe Execution Successful
[2020-03-03T17:22:21.758+00:00] [INFO] [module:cadence-proxy] [index:650] signal completed successfully
[2020-03-03T17:22:21.758+00:00] [INFO] [module:unknown] [context-id:8111dd4e-ef31-41cd-8b45-ad82509b3305] [index:52] Order: o::1bd586ee-4dbc-437f-b086-a7b535c66d11 has been placed.
[2020-03-03T17:22:21.762+00:00] [INFO] [module:unknown] [context-id:8111dd4e-ef31-41cd-8b45-ad82509b3305] [index:53] Customer needs duffel bags.
[2020-03-03T17:22:22.129+00:00] [ERROR] [module:Neon.Cadence.WorkflowBase] [index:2] Neon.Cadence.WorkflowParallelOperationException: Workflows cannot perform multiple operations in parallel.\n   at Neon.Cadence.Workflow.ExecuteNonParallel[TResult](Func`1 actionAsync)\n   at Neon.Cadence.Workflow.ExecuteLocalActivityAsync(Type activityType, ConstructorInfo activityConstructor, MethodInfo activityMethod, Byte[] args, LocalActivityOptions options)\n   at Neon.Cadence.Stubs.ActivityOrder_Stub_14.___StubHelper.ExecuteLocalActivityAsync(Workflow workflow, Type activityType, ConstructorInfo constructor, MethodInfo method, Byte[] args, LocalActivityOptions options)\n   at Neon.Cadence.Stubs.ActivityOrder_Stub_14.CreateOrderAsync(Order order)\n   at WFCustomerAppOrder.WorkflowOrder.ProcessOrderAsync(Order order) in C:\\src\\loopie\\Workflows\\wf-customer-app-order\\WorkflowOrder.cs:line 210\n   at Neon.Common.NeonHelper.GetTaskResultAsObjectAsync(Task task)\n   at Neon.Cadence.WorkflowBase.OnInvokeAsync(CadenceClient client, WorkflowInvokeRequest request)
```

**Comment by marcusbooyah** [comment]
I’m not sure that the first failure is caused by the `WorkflowParallelOperationException`. From the `cadence-proxy` logs, it look like we never see either: `Successfully Signaled Workflow` or 
`signal completed successfully` before the workflow restarts and then I’m seeing the `WorkflowParallelOperationException` On activities called on the replay.

**Comment by jefflill** [comment]
I created a simple workflow unit test (**SyncSignal_Blast**) that starts a workflow and then signals it for a configurable number of times followed by a signal that causes the workflow to exit.

Investigation results so far: 

* This test works fine up to about 1000 signals but then failed yesterday for 2000 signals.

* I thought we could be exceeding the Cadence history limit.  It appears that Cadence generates approximately 4 history events for each decision task executed so the 1000 signal test will result in a history with more than 4000 events.  Cadence supports workflow histories with up to 200K events so we should be fine (I originally thought that Cadence is limited to 10K events, but that was SWF).

  This means Cadence should be able to support about 50K decision tasks per workflow.

* Workflow queries don't generate a history event (as expected).

* Today, I've been able to complete tests sending as many as **8000** signals.  Nothing has changed since yesterday.  I'm starting to doubt that the number of signals sent is causing this.

* I'm starting to think this is some kind of race condition.

I believe @marcusbooyah is executing an activity when signals are received.  I'll add this to my unit test and see what happens.

**Comment by jefflill** [comment]
I'm no longer able to replicate any problems.  I suspect this was working yesterday too.  Perhaps I wasn't waiting long enough for the tests to complete.

**Comment by jefflill** [comment]
I suspect that @marcusbooyah code is throwing an exception somewhere within the workflow/activity and this may be causing his issue.  I just reviewed the `WorkflowBase` and `ActivityBase` classes and found two places where exceptions aren't being logged:

* Exceptions from non-local activities
* Exceptions within from he signal methods

I've added this logging and will include it in an immediate Neon v1.2.2 release

**Comment by jefflill** [comment]
@marcusbooyah: ran some more manual tests and this issue appears to have gone away.
