### ISSUE TITLE
OutOfMemoryException after neonDESKTOP runs for a few hours without a connection

### ISSUE THREAD

**Issue by granth7** [nforgeio/neonKUBE#883]
I have seen this pop up a few times:
![image](https://user-images.githubusercontent.com/30205108/85933101-05c3c300-b888-11ea-9105-68eb41c2e778.png)

In this case neon has been running for a few hours without a connection (neon runs on startup but my vpn doesn't).

Clicking 'details' I get this exception text:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at YamlDotNet.Core.Cursor.Mark()
   at YamlDotNet.Core.Scanner.FetchValue()
   at YamlDotNet.Core.Scanner.FetchNextToken()
   at YamlDotNet.Core.Scanner.FetchMoreTokens()
   at YamlDotNet.Core.Scanner.MoveNextWithoutConsuming()
   at YamlDotNet.Core.Parser.GetCurrentToken()
   at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst)
   at YamlDotNet.Core.Parser.StateMachine()
   at YamlDotNet.Core.Parser.MoveNext()
   at YamlDotNet.Core.ParserExtensions.Allow[T](IParser parser)
   at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
```

Task manager shows neon at the 1.2 GB limit for x86 applications:

![tempsnip](https://user-images.githubusercontent.com/30205108/85933295-50ded580-b88a-11ea-9d32-d7cfbda2e3eb.png)

Any idea why we're running out of memory here? Would it be worth it/possible to compile neon in x64 to increase the memory limit?

**Comment by jefflill** [comment]
I'm going to track this in #433 along with the other major desktop changes.
